In [15]:
import pandas as pd
import time
from events_data_core.spacy_country_recognition import CountryRecognizer

In [16]:
df = pd.read_csv('../data/events/3_countries/2000-2025.csv')

df.head()

,date_start,date_end,event,loc,norm_loc
0,2000-01-01,NaN,Деноминация белорусского рубля;,[],[]
1,2000-01-01,NaN,"В связи с «проблемой-2000», в Иране объявлен н...",['Иране'],['Иран']
2,2000-01-01,NaN,"Вступление в силу закона в Великобритании, сог...",['Великобритании'],['Великобритания']
3,2000-01-02,NaN,крушение украинского сухогруза типа «река-море...,"['Тикси', 'Николаев', 'Камбоджи', 'Туапсе']","['Тикси', 'Николаев', 'Камбоджа', 'Туапсе']"
4,2000-01-03,NaN,Обстрел из гранатомёта территории российского ...,"['Ливане', 'Бейрут']","['Ливана', 'Бейрут']"

In [17]:
recognizer = CountryRecognizer()

start = time.time()
df["country"] = recognizer.match_locations_series(df["event"])
elapsed = time.time() - start

recognized = df["country"].notna().sum()
print(f"Время:     {elapsed:.2f} с")
print(f"Опознано:  {recognized} / {len(df)} строк ({recognized / len(df) * 100:.1f}%)")
df

Время:     27.27 с
Опознано:  3900 / 5630 строк (69.3%)

,date_start,date_end,event,loc,norm_loc,country
0,2000-01-01,NaN,Деноминация белорусского рубля;,[],[],[BELARUS]
1,2000-01-01,NaN,"В связи с «проблемой-2000», в Иране объявлен н...",['Иране'],['Иран'],[IRAN]
2,2000-01-01,NaN,"Вступление в силу закона в Великобритании, сог...",['Великобритании'],['Великобритания'],[UK]
3,2000-01-02,NaN,крушение украинского сухогруза типа «река-море...,"['Тикси', 'Николаев', 'Камбоджи', 'Туапсе']","['Тикси', 'Николаев', 'Камбоджа', 'Туапсе']","[UKRAINE, CAMBODIA]"
4,2000-01-03,NaN,Обстрел из гранатомёта территории российского ...,"['Ливане', 'Бейрут']","['Ливана', 'Бейрут']",[RUSSIA]
...,...,...,...,...,...,...
5625,2025-09-18,NaN,на Камчатке зафиксировано землетрясение магнит...,['Камчатке'],['Камчатка'],None
5626,2025-09-20,NaN,проведение конкурса песни «Интервидение» в Мос...,['Москве'],['Москва'],[RUSSIA]
5627,2025-09-23,NaN,Международный уголовный суд представил подтвер...,['Филиппин'],['Филиппины'],None
5628,2025-09-25,NaN,Парламент Кыргызстана объявил о самороспуске.,['Кыргызстана'],['Кыргызстан'],[KYRGYZSTAN]
5629,2025-09-25,NaN,Бывший президент Франции Николя Саркози пригов...,['Франции'],['Франция'],[FRANCE]