In [1]:
import re

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/events/2_struct/2000-2025.csv')

df.head()

   date_start date_end                                              event
0  2000-01-01      NaN                    Деноминация белорусского рубля;
1  2000-01-01      NaN  В связи с «проблемой-2000», в Иране объявлен н...
2  2000-01-01      NaN  Вступление в силу закона в Великобритании, сог...
3  2000-01-02      NaN  крушение украинского сухогруза типа «река-море...
4  2000-01-03      NaN  Обстрел из гранатомёта территории российского ...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5641 entries, 0 to 5640
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date_start  5641 non-null   object
 1   date_end    602 non-null    object
 2   event       5641 non-null   object
dtypes: object(3)
memory usage: 132.3+ KB

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

ru_stopwords = stopwords.words("russian")


def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"[^а-яё\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


texts = df["event"].dropna().astype(str).apply(clean_text)

vectorizer = TfidfVectorizer(
    max_df=0.9,
    min_df=5,
    stop_words=ru_stopwords,
    ngram_range=(1, 3),
    sublinear_tf=True,
)
X = vectorizer.fit_transform(texts)

n_topics = 10
model = NMF(n_components=n_topics, random_state=42)
W = model.fit_transform(X)
H = model.components_

feature_names = vectorizer.get_feature_names_out()
topics = {}
for i, topic in enumerate(H):
    top_words = [feature_names[j] for j in topic.argsort()[:-11:-1]]
    topics[f"Topic {i + 1}"] = top_words

print(len(vectorizer.vocabulary_))
topics

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ruslan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

3313

{'Topic 1': ['парламентские выборы',
  'парламентские',
  'выборы',
  'досрочные парламентские',
  'досрочные парламентские выборы',
  'досрочные',
  'партия',
  'большинство',
  'сирии',
  'мест'],
 'Topic 2': ['человек',
  'погибли',
  'погибли человек',
  'результате',
  'человека',
  'человек погибли',
  'получили',
  'ранения',
  'ранены',
  'погибло'],
 'Topic 3': ['должность',
  'вступил',
  'должность президента',
  'президента',
  'вступил должность',
  'вступил должность президента',
  'года',
  'президент',
  'должность президент',
  'вступил должность президент'],
 'Topic 4': ['тур',
  'выборов',
  'президентских',
  'президентских выборов',
  'второй',
  'второй тур',
  'тур президентских',
  'тур президентских выборов',
  'второй тур президентских',
  'одержал'],
 'Topic 5': ['мира',
  'чемпионат',
  'чемпионат мира',
  'россия',
  'мира хоккею',
  'хоккею',
  'чемпионат мира хоккею',
  'сборная',
  'шайбой',
  'хоккею шайбой'],
 'Topic 6': ['премьер',
  'министром',
  'премьер министром',
  'стал',
  'новым',
  'новым премьер',
  'новым премьер министром',
  'министра',
  'премьер министра',
  'назначен'],
 'Topic 7': ['сша',
  'союз',
  'корабля',
  'экипаж',
  'корабля союз',
  'тма',
  'союз тма',
  'космического',
  'космического корабля',
  'космического корабля союз'],
 'Topic 8': ['президентские',
  'президентские выборы',
  'выборы',
  'одержал',
  'победу одержал',
  'победу',
  'президент',
  'действующий',
  'действующий президент',
  'избран'],
 'Topic 9': ['россии',
  'день',
  'единый',
  'голосования',
  'против',
  'день голосования',
  'единый день',
  'единый день голосования',
  'день голосования россии',
  'голосования россии'],
 'Topic 10': ['одержала',
  'победу',
  'победу одержала',
  'партия',
  'правящая',
  'парламентских',
  'сборная',
  'одержала правящая',
  'победу одержала правящая',
  'оппозиционная']}

In [5]:
from sklearn.decomposition import TruncatedSVD

n_topics = 10

lsa = TruncatedSVD(
    n_components=n_topics,
    random_state=42
)

X_lsa = lsa.fit_transform(X)
feature_names = vectorizer.get_feature_names_out()

topics = {}

for i, comp in enumerate(lsa.components_):
    indices = np.argsort(np.abs(comp))[-12:]
    top_words = [feature_names[j] for j in indices]
    topics[f"Topic {i + 1}"] = top_words

topics

{'Topic 1': ['тур',
  'победу одержала',
  'победу одержал',
  'одержал',
  'одержала',
  'партия',
  'президентские выборы',
  'президентские',
  'победу',
  'парламентские выборы',
  'парламентские',
  'выборы'],
 'Topic 2': ['президента',
  'погибло',
  'получили ранения',
  'ранены',
  'ранения',
  'получили',
  'человек погибли',
  'человека',
  'результате',
  'погибли человек',
  'погибли',
  'человек'],
 'Topic 3': ['одержал',
  'погибли',
  'человек',
  'тур',
  'выборов',
  'парламентские',
  'парламентские выборы',
  'вступил должность',
  'должность президента',
  'вступил',
  'президента',
  'должность'],
 'Topic 4': ['одержал',
  'победу',
  'второй',
  'президентских выборов',
  'второй тур',
  'президентских',
  'вступил должность',
  'должность президента',
  'выборов',
  'тур',
  'вступил',
  'должность'],
 'Topic 5': ['шайбой',
  'мира хоккею шайбой',
  'хоккею шайбой',
  'одержала',
  'чемпионат мира хоккею',
  'мира хоккею',
  'хоккею',
  'сборная',
  'россия',
  'чемпионат мира',
  'чемпионат',
  'мира'],
 'Topic 6': ['министра',
  'президента',
  'вступил',
  'должность',
  'должность президента',
  'новым премьер',
  'новым премьер министром',
  'новым',
  'стал',
  'премьер министром',
  'министром',
  'премьер'],
 'Topic 7': ['тма экипаж',
  'корабля союз тма',
  'космического корабля союз',
  'космического корабля',
  'космического',
  'союз тма',
  'тма',
  'корабля союз',
  'экипаж',
  'корабля',
  'союз',
  'сша'],
 'Topic 8': ['тур президентских',
  'победу одержал',
  'одержал',
  'тур',
  'президентских',
  'президентских выборов',
  'выборов',
  'выборы',
  'парламентские',
  'парламентские выборы',
  'президентские',
  'президентские выборы'],
 'Topic 9': ['силу',
  'закон',
  'голосования россии',
  'день голосования россии',
  'против',
  'единый день голосования',
  'день голосования',
  'единый день',
  'голосования',
  'единый',
  'день',
  'россии'],
 'Topic 10': ['первый',
  'выборы',
  'тур',
  'президента',
  'победу одержал',
  'одержал',
  'президентские',
  'президентские выборы',
  'партия',
  'победу одержала',
  'одержала',
  'победу']}

In [6]:
from sklearn.decomposition import LatentDirichletAllocation

n_topics = 10
lda = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    learning_method="batch",
    max_iter=30,
    doc_topic_prior=0.1,  # alpha
    topic_word_prior=0.01  # beta
)
X_lda = lda.fit_transform(X)

feature_names = vectorizer.get_feature_names_out()
topics = {}
for i, topic_dist in enumerate(lda.components_):
    top_idx = topic_dist.argsort()[-12:][::-1]
    topics[f"Topic {i + 1}"] = [feature_names[j] for j in top_idx]

topics

{'Topic 1': ['сша',
  'союз',
  'корабля',
  'экипаж',
  'тма',
  'союз тма',
  'космического',
  'космического корабля',
  'корабля союз',
  'владимир',
  'космический',
  'путин'],
 'Topic 2': ['премьер',
  'министром',
  'премьер министром',
  'стал',
  'отставку',
  'министр',
  'премьер министр',
  'новым',
  'президент',
  'новым премьер',
  'новым премьер министром',
  'лидер'],
 'Topic 3': ['космодрома',
  'запуск',
  'открытие',
  'мире',
  'казахстан',
  'официально',
  'саммит',
  'впервые',
  'стала',
  'байконур',
  'космодрома байконур',
  'истории'],
 'Topic 4': ['россии',
  'начало',
  'территории',
  'кндр',
  'первого',
  'сша',
  'лет',
  'стран',
  'сирии',
  'решение',
  'государств',
  'власти'],
 'Topic 5': ['выборы',
  'парламентские',
  'парламентские выборы',
  'победу',
  'президентские',
  'президентские выборы',
  'партия',
  'одержал',
  'победу одержал',
  'президента',
  'тур',
  'выборов'],
 'Topic 6': ['убийство',
  'открыт',
  'нато',
  'должность президент',
  'взрыв',
  'центре',
  'санкт',
  'украину',
  'россии',
  'вступил должность президент',
  'станции',
  'массовое'],
 'Topic 7': ['человек',
  'погибли',
  'результате',
  'погибли человек',
  'человека',
  'погибло',
  'ранены',
  'получили',
  'человек погибли',
  'ранения',
  'около',
  'получили ранения'],
 'Topic 8': ['силу',
  'российской',
  'россии',
  'день',
  'федерации',
  'международный',
  'вступил',
  'российской федерации',
  'отношения',
  'вступил силу',
  'дипломатические',
  'протеста'],
 'Topic 9': ['мира',
  'чемпионат',
  'чемпионат мира',
  'тур президентских',
  'тур президентских выборов',
  'президентских выборов',
  'россия',
  'европы',
  'президентских',
  'тур',
  'сборная',
  'выборов'],
 'Topic 10': ['должность',
  'вступил',
  'президента',
  'должность президента',
  'вступил должность',
  'президентом',
  'вступил должность президента',
  'года',
  'министра',
  'премьер министра',
  'компания',
  'игры']}

In [7]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

texts = df["event"]

embedding_model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

vectorizer_model = CountVectorizer(
    ngram_range=(1, 3),
    min_df=5
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True,
)

topics, probs = topic_model.fit_transform(texts)

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

2026-02-24 17:20:45,928 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-02-24 17:21:41,766 - BERTopic - Embedding - Completed ✓
2026-02-24 17:21:41,767 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-24 17:22:00,058 - BERTopic - Dimensionality - Completed ✓
2026-02-24 17:22:00,060 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-24 17:22:03,038 - BERTopic - Cluster - Completed ✓
2026-02-24 17:22:03,043 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-24 17:22:03,437 - BERTopic - Representation - Completed ✓

In [8]:
import random
from collections import defaultdict


def sample_docs_per_topic(texts, topics, n_samples=10, seed=42):
    random.seed(seed)

    topic_to_docs = defaultdict(list)
    for text, topic in zip(texts, topics):
        topic_to_docs[topic].append(text)

    for topic_id, docs in sorted(topic_to_docs.items()):
        if topic_id == -1:
            print(f"topic {topic_id} | total docs: {len(docs)}")
            continue

        print("=" * 80)
        print(f"TOPIC {topic_id} | total docs: {len(docs)}")
        print("=" * 80)

        sampled = random.sample(docs, min(n_samples, len(docs)))
        for i, doc in enumerate(sampled, 1):
            print(f"{i}. {doc}")
        print()


def save_topics_barchart(topic_model: BERTopic, out_html="topics_barchart.html", top_n_topics=30):
    """
    Сохраняет интерактивный bar chart с размерами/словами тем (BERTopic).
    """
    fig = topic_model.visualize_barchart(top_n_topics=top_n_topics, n_words=10)
    fig.write_html(out_html)
    return fig


def save_documents_scatter(topic_model, texts, topics, out_html="documents_scatter.html"):
    """
    Сохраняет интерактивный scatter документов по темам (BERTopic).
    """
    fig = topic_model.visualize_documents(docs=texts, topics=topics)
    fig.write_html(out_html)
    return fig

In [9]:
topic_model.get_topic_info().head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1588,-1_по_выборы_победу_парламентские,"[по, выборы, победу, парламентские, парламентс...",[чемпионат мира по современному пятиборью (Тай...
1,0,131,0_протеста_против_массовые_начались,"[протеста, против, массовые, начались, беспоря...",[В Абхазии начались акции протеста оппозиции с...
2,1,107,1_союз_корабля_космического корабля_космического,"[союз, корабля, космического корабля, космичес...",[приземление космического корабля Союз ТМА-01М...
3,2,106,2_результате взрыва_взрыва_результате_погибли,"[результате взрыва, взрыва, результате, погибл...",[В результате взрыва на химическом заводе во ф...
4,3,101,3_сербии_хорватии_словакии_македонии,"[сербии, хорватии, словакии, македонии, парлам...",[Парламентские выборы в Румынии. По предварите...
5,4,99,4_самолёт_борту_на борту_все,"[самолёт, борту, на борту, все, катастрофа, са...",[Авиакатастрофа в Индонезии. Самолёт Boeing 73...
6,5,83,5_сша_президент сша_дональда_представителей,"[сша, президент сша, дональда, представителей,...",[Президент США Барак Обама подписал «Закон о д...
7,6,82,6_саммит_конференция_государств_глав,"[саммит, конференция, государств, глав, нато, ...","[саммит ШОС в Самарканде., саммит АТЭС (Манила..."
8,7,79,7_произошло_землетрясения_человек_более,"[произошло, землетрясения, человек, более, без...",[В Тбилиси произошло землетрясение магнитудой ...
9,8,73,8_сирии_войска_ирака_аль,"[сирии, войска, ирака, аль, коалиции, террорис...",[Беспилотник США в Ракке в ходе атаки ликвидир...

In [10]:
sample_docs_per_topic(texts, topics, n_samples=10)
save_topics_barchart(topic_model, out_html="topic_plots/topics_barchart_auto.html")
save_documents_scatter(topic_model, texts, topics, out_html="topic_plots/documents_scatter_auto.html")

topic -1 | total docs: 1588
================================================================================
TOPIC 0 | total docs: 131
================================================================================
1. в Калининграде состоялся крупнейший в России с 1990-х годов митинг протеста против действия властей.
2. на Пушкинской площади прошёл митинг в защиту свободы слова и телекомпании НТВ, организованный партией «Яблоко», СПС и Союзом журналистов России. В нём приняли участие 20 тыс. человек.
3. В Архангельске прошла несанкционированная властями акция протеста (марш и митинг) против строительства на станции «Шиес» полигона для мусора из Москвы;
4. Акции протеста против коррупции в высших эшелонах российской власти, прошедшие в десятках городов России.
5. В Белоруссии начались протесты против президентского указа № 222.
6. В столице Анголы Луанде разогнана антиправительственная демонстрация во главе с рэпером Иконокластой.
7. массовые беспорядки в Иране.
8. массовые беспорядки в Кондопоге (Россия).
9. антисемитские беспорядки в махачкалинском аэропорту Уйташ.
10. Расстрел демонстрации в селе Аксы, Джалал-Абадской области Кыргызстана, протестовавшей против передачи части киргизских территорий Китаю.

================================================================================
TOPIC 1 | total docs: 107
================================================================================
1. Старт космического корабля Союз ТМ-31 с первым экипажем МКС на борту. Экипаж старта — Ю. П. Гидзенко, С. К. Крикалёв и У. Шеперд (США);
2. приземление корабля Союз ТМ-34. Экипаж посадки — Ю. В. Лончаков, С. В. Залётин и Франк Де Винне (Бельгия).
3. приземление космического корабля Союз ТМА-7. Экипаж посадки — В. И. Токарев, У. МакАртур (США) и М. Понтис (Бразилия).
4. Приземление космического корабля Союз ТМА-8. Экипаж посадки — П. В. Виноградов, Д. Уильямс (США) и А. Ансари (Иран-США).
5. приземление космического корабля Союз ТМА-21. Экипаж посадки — Андрей Борисенко, Александр Самокутяев и Рональд Гаран (США).
6. старт космического корабля Союз ТМА-08М к международной космической станции. Экипаж: Павел Виноградов, Александр Мисуркин (оба Россия), Кристофер Кэссиди (США).
7. с космодрома Байконур стартовал транспортный пилотируемый корабль Союз ТМА-05М. Экипаж старта — Юрий Маленченко, Сунита Уильямс (США) и Акихико Хосидэ (Япония).
8. приземлился космический корабль «Союз ТМА-6» с международным экипажем.
9. Запущен космический корабль «Союз ТМА-20М» с экипажем в составе: Алексей Овчинин, Олег Скрипочка, Джеффри Уильямс.
10. космический корабль Союз ТМА-11М совершил посадку в Казахстане, Экипаж посадки: Михаил Тюрин (ФКА), Ричард Мастраккио (НАСА) и Коити Ваката (JAXA).

================================================================================
TOPIC 2 | total docs: 106
================================================================================
1. взрыв бомбы возле школы в Кабуле (Исламская Республика Афганистан), в результате которого погибло не менее 85 человек и ещё 147 получили ранения.
2. в результате стрельбы в Копенгагене (Дания) погибли 3 и ранены 5 человек.
3. взрыв метана на угольной шахте «Ульяновская» в Кемеровской области. Спасено 93 человека, число погибших составило 110 человек.
4. Война в Афганистане: в результате взрыва бомбы в Кабуле погибли 22 человека.
5. Взрыв в маршрутном такси в Дагестане, произведённый террористкой-смертницей, 1 человек погиб и 8 получили ранения.
6. на расположенной в посёлке Северный шахте «Северная» компании «Воркутауголь» зафиксирован горный удар. В аварии погибли 36 человек, среди которых как шахтёры, так и спасатели.
7. в результате схода селя в курортной зоне индонезийской провинции Восточная Ява 22 человека погибли, 4 получили ранения.
8. Теракт в Новом Орлеане. Погибли 15 человек (включая напавшего), пострадали 45.
9. При взрыве в шахте «Баракова» в Краснодоне погиб 81 шахтёр. Самые тяжёлые последствия от аварии на Украине за 20 лет.
10. Взрыв на автозаправочной станции в Махачкале. Погибли 37 человек, около 100 пострадали.

================================================================================
TOPIC 3 | total docs: 101
================================================================================
1. В Черногории состоялись президентские выборы. Больше всех голосов получил премьер-министр Филип Вуянович (83,65 % голосов избирателей), однако из-за низкой явки (45,87 % при необходимой явке не менее 50 %) выборы были признаны недействительными.
2. внеочередные выборы в Народную скупщину (парламент) Сербии.
3. Президентские выборы в Македонии. По предварительным данным, лидирует действующий президент Георге Иванов.
4. Досрочные парламентские выборы в Словакии. По предварительным данным, лидирует социал-демократическая партия Smer-SD.
5. первый тур президентских выборов в Республике Македонии.
6. во втором туре президентских выборов в Словении премьер-министр Янез Дрновшек получил 56,6 % голосов и был избран президентом страны.
7. прошли парламентские выборы в Польше. Победила партия Ярослава Качиньского «Право и Справедливость» (пол. Prawo i Sprawiedliwość) с результатом 26,99 %, на втором месте «Гражданская Платформа» (пол. Platforma Obywatelska) Дональда Туска — 24,14 %, затем «Самооборона» Анджея Леппера — 11,41 %.
8. второй тур президентских выборов в Хорватии. На второй срок переизбран президент страны Зоран Миланович.
9. коалиция СДЛС и Унии труда победила на парламентских выборах в Польше, получив (41,04 %) голосов, 216 из 460 мест в Сейме и 75 из 100 — в Сенате.
10. на парламентских выборах в Сербии так же, как и в СРЮ, победила коалиция оппозиционных партий, получившая 64,1 % голосов (176 депутатских мандатов), социалистов поддержали 13,8 % избирателей (37 мест), Сербскую радикальную партию — 8,6 % (23 места), Партию сербского единства убитого незадолго до этого Ж. Ражнатовича-Аркана — 5,3 % (14 мест).

================================================================================
TOPIC 4 | total docs: 99
================================================================================
1. При посадке в норвежском аэропорту Стур произошла катастрофа самолёта BAe 146 компании Atlantic Airways, погибли 4 человека.
2. аварийная посадка Ту-204 в Омске, пострадавших нет.
3. в Лексингтоне (Кентукки) при взлёте разбился самолёт Bombardier CRJ-100ER компании Comair, погибли 49 человек.
4. в 2.15 по московскому времени в районе Сочи разбился пассажирский самолёт А-320 армянской авиакомпании «Армавиа», выполнявший рейс Ереван—Сочи. Все 113 человек, находившиеся на борту, погибли. Самолёт, выполняя заход на посадку в сложных метеоусловиях, упал в море.
5. авиакатастрофа Boeing 737 авиакомпании Lion Air в районе Джакарты; 189 погибших.
6. катастрофа Boeing 737 под Шарм-эш-Шейхом.
7. В аэропорту имени Чан Кайши при взлёте разбился Boeing 747 компании Singapore Airlines, погибли 83 из 179 человек на борту.
8. Авиакатастрофа в Вашингтоне из-за столкновения самолёта Bombardier CRJ700 с вертолётом Sikorsky UH-60 Black Hawk над рекой Потомак. В результате столкновения погибли все 67 пассажиров на борту.
9. В столице ДРК городе Киншасе произошла авиакатастрофа самолёта «CRJ-100». Погибли 32 человека.
10. в Малайзии при пролёте над Южно-Китайским морем пропал с экранов радаров самолёт Boeing 777—200 авиакомпании Malaysia Airlines c 227 пассажирами и 12 членами экипажа на борту.

================================================================================
TOPIC 5 | total docs: 83
================================================================================
1. Джордж Буш (младший) вступил в должность президента США на второй срок.
2. США вышли из Договора по открытому небу.
3. Президент США Джордж Буш объявил о намерении Соединённых Штатов снова стать членом ЮНЕСКО, из состава которой они вышли 18 лет назад (США восстановлены в ЮНЕСКО 29 сентября 2003 года).
4. В возрасте 100 лет скончался 39-й президент США и лауреат Нобелевской премии мира — Джимми Картер. Картер стал самым долгоживущим президентом США и единственным который дожил до 100 лет. Государственные похороны прошли 9 января 2025 года.
5. выборы президента, всех членов Палаты представителей и трети сенаторов США. На президентских выборах победу одержал республиканец Дональд Трамп.
6. Дональд Трамп заявил о прекращении вмешательства США в военные конфликты других стран.
7. инаугурация 47-го президента США Дональда Трампа.
8. инаугурация президента США Барака Обамы.
9. США в одностороннем порядке вышли из Договора о противоракетной обороне от 1972 года.
10. Джордж Буш подписал «Патриотический акт», давший правоохранительным органам страны широкие полномочия в борьбе с терроризмом.

================================================================================
TOPIC 6 | total docs: 82
================================================================================
1. саммит АТЭС (Гонолулу, США).
2. саммит G-20 в Брисбене (Австралия).
3. в Санкт-Петербурге состоялся саммит глав стран «Большой восьмёрки».
4. саммит НАТО в Нидерландах.
5. в Вашингтоне состоялся 3-й Solar Decathlon.
6. В Берлине состоялось заседание Нормандской четвёрки.
7. Основная статья: Февраль 2014 года
8. стратегические командно-штабные учения (СКШУ) Центр-2019.
9. саммит G20 (Ханчжоу, КНР).
10. Роспуск Нидерландских Антильских островов.

================================================================================
TOPIC 7 | total docs: 79
================================================================================
1. землетрясение магнитудой 6,4 в Албании, погиб 51 человек.
2. Землетрясение и цунами на Сулавеси, Индонезия. По меньшей мере 4340 человек погибло и 10 679 человек получили ранения.
3. повторное землетрясение на севере Италии магнитудой 5,8. Погибли 20 человек. Многим историческим зданиям нанесён урон.
4. в Непале и Индии произошло повторное землетрясение магнитудой 7,4. В Непале погибли 117 человек, ещё 1926 пострадали; в Индии погибли 17 человек, ещё один человек погиб на территории Китая.
5. Крупнейшее землетрясение в Индийском океане у берегов Юго-Восточной Азии. В результате цунами погибли около 230 тысяч человек.
6. землетрясение магнитудой от 9,0 до 9,1 произошло у северо-восточного побережья Японии. Землетрясение вызвало разрушительное цунами в Японии. Высота волны достигала 10 м. Произошли сбои в работе нескольких ядерных реакторов. 15 597 погибших, 5694 раненых, 4980 пропавших без вести (на 20 июля). Экономический ущерб, по приблизительной оценке, составил до 309 млрд USD.
7. серия землетрясений на Тайване магнитудой 7,4 и 6,5 балла. 18 погибших 1,147 раненых
8. в Охотском море произошло землетрясение магнитудой 6,9 на глубине свыше 600 км. Отголоски этого землетрясения ощущались на большей части России.
9. В результате разрушительного землетрясения в Крайстчерче (Новая Зеландия) магнитудой 6,3 погибли 166 человек, 122 — пропали без вести.
10. Мощное землетрясение в Турции, Сирии, Ливане, сильные и слабые землетрясения в других странах в разных частях света. Погибло более 52 000 человек, более 122 000 человек получили ранения различной тяжести.

================================================================================
TOPIC 8 | total docs: 73
================================================================================
1. Нападение на посольство США в Багдаде;
2. боевики ИГИЛ объявили об упразднении границы Ирака и Сирии, крахе системы Сайкска-Пико и эпохи колониализма на Ближнем Востоке, и провозгласили себя Халифатом.
3. Начало гражданской войны в Сирии.
4. Правительственные войска Ирака начали операцию в Иракском Курдистане, заняв Киркук.
5. Войска коалиции заняли Багдад. США объявили о взятии Багдада и свержении Саддама Хусейна.
6. Военно-воздушные силы Франции, Великобритании и США начали бомбардировки районов Ливии, находящихся под контролем сторонников Каддафи.
7. авиация США и Великобритании нанесла бомбовые удары по мобильной ракетной системе ПРО «земля-воздух» к югу от иракского города Аль-Амарах.
8. Беспилотник США в Ракке в ходе атаки ликвидировал террористку Салли Джонс («Белую вдову»), воевавшую на стороне террористической организации «Исламское государство» в Сирии.
9. Несколько военных объектов США на территории Ирака атакованы Корпусом стражей исламской революции (КСИР) Ирана. Корпус стражей исламской революции взял на себя ответственность за удар по американской авиабазе в Ираке, уточнив, что это месть за убийство американскими военными генерала Касема Сулеймани.
10. Иран нанёс ракетные удары по американским военным базам в Катаре и Ираке в ответ на авиаудары США, совершённые накануне.

================================================================================
TOPIC 9 | total docs: 72
================================================================================
1. Камчатская область и Корякский автономный округ объединились в Камчатский край.
2. Вооружённый конфликт на востоке Украины: Народная милиция ДНР в ходе ожесточённых боёв, взяла под свой контроль старый терминал аэропорта «Донецк».
3. признание Россией Донецкой и Луганской Народных Республик.
4. ВС РФ освободили город Суджа в Курской области.
5. Начался вывод российских миротворцев из Нагорного Карабаха.
6. В России объявлена мобилизация.
7. столицей оккупированной Россией части Запорожской области официально стал Мелитополь.
8. Территория Москвы увеличилась почти в 2,5 раза — со 107 тыс. га до 255 тыс. га за счёт присоединения части территории Московской области.
9. Россия передала захваченные в Керченском проливе корабли (катера «Никополь» и «Бердянск» и буксир «Яны Капу») Украине;
10. Россия объявила о полном освобождении Курской области от вооружённых сил Украины.

================================================================================
TOPIC 10 | total docs: 70
================================================================================
1. С космодрома Куру во Французской Гвиане европейский концерн Arianespace запустил ракету Ариан-5.
2. В США состоялся первый пилотируемый запуск космического корабля Starliner в рамках миссии Boe-CFT.
3. с космодрома Байконур стартовала ракета-носитель «Протон-М» с разгонным блоком «Бриз-М» и американским телекоммуникационным спутником «Sirius XM-5».
4. после ремонта и модернизации вновь запущен Большой адронный коллайдер.
5. стартовавшая с космодрома «Плесецк» ракета-носитель «Рокот» вывела на орбиту три спутника связи «Гонец-М».
6. c космодрома Куру (Французская Гвиана) запущен первый искусственный спутник Земли Катара «Сухейль-1».
7. с космодрома Байконур стартовала ракета-носитель «Протон-М» с американским спутником связи «EchoStar-14».
8. спущен на воду вертолётоносец «Мистраль», первый в одноимённой серии.
9. с космодрома Байконур стартовала ракета-носитель класса Протон-М с тремя спутниками Глонасс-М.
10. Компания SpaceX впервые успешно вернула на стартовую площадку первую ступень сверхтяжёлой ракеты-носителя Starship, самой большой и мощной из когда-либо запущенных ракет.

================================================================================
TOPIC 11 | total docs: 68
================================================================================
1. в Багдаде во время религиозных мероприятий на мосту через реку Тигр вспыхнула паника. Из-за слуха о террористах-самоубийцах в давке погибли более 1000 человек.
2. взрывы прогремели в центральных районах Багдада у штаб-квартиры Красного Креста, здания министерства промышленности и полицейского участка. Для атак террористы использовали начинённые взрывчаткой автомобили. 35 человек погибли, более 200 получили ранения.
3. беспорядки в Ингушетии. В ходе беспорядков арестовано около 100 человек.
4. Взрыв в коптской церкви в Александрии (Египет). Погибли 23 человека, ранены 97 человек.
5. Нападение радикальных исламистов на церковь Мари-Мина в Египте. Погибли 12 человек и 232 ранены.
6. в результате нападения исламистов в Мали погибли 8 миротворцев ООН.
7. в результате двух взрывов в столице Ирака Багдаде погибли около 300 человек.
8. в Ираке прошла серия терактов в разных городах. Погибли 66 человек, ранено более 100.
9. Теракты в шиитском районе Бейрута. Погибли 43, ранены 239 человек.
10. Бойня в Кисангани — после попытки неудачного восстания в городе Кисангани (ДР Конго) были убиты около 200 человек (солдаты РКД, полицейские и мирные граждане).

================================================================================
TOPIC 12 | total docs: 65
================================================================================
1. Вторая чеченская война: ликвидирован президент Ичкерии Аслан Масхадов.
2. Вторая чеченская война: 400 боевиков атаковали Грозный.
3. Вторая чеченская война: вертолёт Ми-8МТ ВС РФ был сбит из ПЗРК возле Ханкалы. 9 человек погибли.
4. Вторая чеченская война: в районе села Бешил-Ирзу из ПЗРК сбит вертолёт Ми-24П ВС РФ. Оба члена экипажа погибли.
5. Вторая чеченская война: в центре Махачкалы убит начальника Управления по борьбе с экстремизмом и уголовным терроризмом МВД Дагестана Ахвердилав Акилов.
6. Вторая чеченская война: в Шелковском районе Чечни сбит вертолёт Ми-8. В числе погибших — заместитель министра внутренних дел РФ генерал-лейтенант Михаил Рудченко и командующий группировкой внутренних войск МВД в Чечне генерал-майор Николай Горидов.
7. Вторая чеченская война: в районе Комсомольского разбился вертолёт Ми-8МТВ-2 МВД России: он зацепился за линию электропередач, уклоняясь от обстрела с земли. 3 человека погибли.
8. произошла авиакатастрофа под Смоленском. В авиакатастрофе погибли президент Польши Лех Качиньский с супругой, глава Генштаба Польши Франтишек Гонгор, глава Национального банка Польши Славомир Скшипек и др.
9. Вторая чеченская война: прорыв боевиков в Шали и Аргун. Контроль федеральных сил над Шали был восстановлен 11 января, над Аргуном — 13 января.
10. в авиакатастрофе погиб президент Македонии Борис Трайковский.

================================================================================
TOPIC 13 | total docs: 63
================================================================================
1. В рамках программы «Аврора» с космодрома Байконур запущена марсианская орбитальная станция «ЭкзоМарс» для поиска следов жизни.
2. Космический зонд «Генезис» с образцами частиц солнечного ветра на борту совершил неудачную посадку.
3. специалисты НАСА обнаружили доказательства наличия на Марсе потоков солёной воды.
4. состоялся запуск американской межпланетной станции «Марс-2020».
5. запуск спутников Van Allen Probes для изучения воздействия солнечной радиации на магнитосферу Земли.
6. космический аппарат «Кассини», после изучения Сатурна и его системы в течение 13 лет, уничтожен путём погружения в атмосферу Сатурна.
7. с космодрома Канаверал с помощью ракеты-носителя Дельта-2 запущена американская АМС Phoenix, предназначенная для исследования Марса.
8. НАСА США отправила на Марс миссию InSight.
9. космический аппарат Dawn достиг Цереры и перешёл на круговую орбиту вокруг этой карликовой планеты.
10. Авария на Большом адронном коллайдере.

================================================================================
TOPIC 14 | total docs: 60
================================================================================
1. Убийство Крейга Зоргера.
2. Массовое убийство в Ставрополе.
3. нападение на школу в Перми (15 пострадавших).
4. в Санкт-Петербурге совершено убийство восьмилетней таджикской девочки Хуршеды Султоновой. Преступление вызвало глубокий общественный резонанс. Вся история получила в СМИ название «Убийство таджикской девочки».
5. Стрельба в средней школе Марджори Стоунман Дуглас, погибло 17 человек, 14 госпитализированы.
6. убийство Виктории Климби в Лондоне. Восьмилетняя ивуарийская девочка подверглась пыткам и была убита собственными опекунами. Публичное расследование её смерти стало поводом для серьёзных изменений в политике по защите детей в Великобритании.
7. В результате стрельбы в начальной школе Белграда погибло 9 человек, 6 ранено.
8. 14 человек погибли и ещё четверо получили ранения в результате стрельбы в Цетине, Черногория.

In [11]:
# semi-supervised learning
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True,
    zeroshot_topic_list=[
        'природная катастрофа', 'авиакатастрофа', 'государственный переворот', 'вооруженный конфликт', 'теракт', 'протесты', 'санкции', 'спорт', 'закон'
    ],
    seed_topic_list=[
        ["землетрясение", "цунами", "извержение вулкана", "ураган", "тайфун",
         "наводнение", "оползень", "сель", "засуха", "лесной пожар"],
        ["авиакатастрофа", "крушение самолета", "пассажирский самолет",
         "на борту", "рейс", "экипаж"],
        ["государственный переворот", "госпереворот", "военный переворот",
 "свержение власти", "захват власти", "путч"],
        ["вооруженный конфликт", "война", "военные действия", "наступление", "обстрел", "ВС РФ", "ВСУ"],
        ["теракт", "смертник", "террористический акт"],
        ["санкции", "пакет санкций"],
        ["акция протеста", "протест", "массовые протесты", "беспорядки"],
        ["запуск ракеты", "космос", "спутник", "космический аппарат", "орбита", "космодром"],
        ["чемпионат мира", "спорт", "золотая медаль", "олимпийские игры", "сборная"],
        ["выборы президента", "выборы премьер-министра", "парламентские выборы"],
        ["закон", "подписание закона", "вступление в силу закона", "законопроект", "принятие закона"],
        ["Nvidia", "Microsoft", "Google", "Samsung", "Huawei", "Facebook", "Apple"]
    ]
)

topics, probs = topic_model.fit_transform(texts)

2026-02-24 17:23:06,664 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-02-24 17:24:14,084 - BERTopic - Embedding - Completed ✓
2026-02-24 17:24:14,085 - BERTopic - Guided - Find embeddings highly related to seeded topics.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-02-24 17:24:14,284 - BERTopic - Guided - Completed ✓
2026-02-24 17:24:14,285 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-24 17:24:17,728 - BERTopic - Dimensionality - Completed ✓
2026-02-24 17:24:17,729 - BERTopic - Zeroshot Step 1 - Finding documents that could be assigned to either one of the zero-shot topics
2026-02-24 17:24:17,854 - BERTopic - Zeroshot Step 1 - Completed ✓
2026-02-24 17:24:29,568 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-24 17:24:31,162 - BERTopic - Cluster - Completed ✓
2026-02-24 17:24:31,164 - BERTopic - Zeroshot Step 2 - Combining topics from zero-shot topic modeling with topics from clustering...
2026-02-24 17:24:31,178 - BERTopic - Zeroshot Step 2 - Completed ✓
2026-02-24 17:24:31,179 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-24 17:24:31,502 - BERTopic - Representation - Completed ✓

In [12]:
topic_model.reduce_topics(
    texts,
    nr_topics=15
)

topics, probs = topic_model.transform(texts)
topic_model.get_topic_info()

2026-02-24 17:24:31,929 - BERTopic - Topic reduction - Reducing number of topics
2026-02-24 17:24:32,144 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-24 17:24:32,399 - BERTopic - Representation - Completed ✓
2026-02-24 17:24:32,402 - BERTopic - Topic reduction - Reduced number of topics from 92 to 15

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-02-24 17:25:36,188 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1428,-1_на_по_выборов_президента,"[на, по, выборов, президента, победу, россии, ...",[второй тур президентских выборов в Румынии. П...
1,0,1375,0_человек_результате_на_россии,"[человек, результате, на, россии, более, погиб...",[Обрушение многоэтажного жилого дома Майами. П...
2,1,894,1_победу_премьер_президента_выборов,"[победу, премьер, президента, выборов, тур, по...",[второй тур выборов президента Финляндии. Побе...
3,2,625,2_союз_человек_на_человека,"[союз, человек, на, человека, все, сша, из, ст...",[легкомоторный самолёт авиакомпании Lion Air I...
4,3,396,3_мира_по_саммит_европы,"[мира, по, саммит, европы, международный, побе...","[чемпионат мира по хоккею с шайбой., Чемпионат..."
5,4,348,4_протеста_против_массовые_президента,"[протеста, против, массовые, президента, проте...",[в России состоялись акции протеста против фал...
6,5,237,5_премьер_союза_президент_югославии,"[премьер, союза, президент, югославии, ес, евр...",[Польша стала государством-председателем Совет...
7,6,82,6_компания_выход_китая_сша,"[компания, выход, китая, сша, китае, китай, по...",[Компания «Microsoft» выпустила операционную с...
8,7,71,7_израиль_израиля_оон_сша,"[израиль, израиля, оон, сша, газа, отношения, ...",[Израиль возобновил удары по сектору Газа посл...
9,8,69,8_закон_силу_об_вступил силу,"[закон, силу, об, вступил силу, договор, подпи...",[вступил в силу принятый в Грузии Закон об ино...
10,9,66,9_принятие_против_сша_россии,"[принятие, против, сша, россии, запрет, на, вс...",[Принятие четвертого пакета санкций против Рос...
11,10,33,10_19_коронавируса_млн_мире,"[19, коронавируса, млн, мире, пандемии, органи...",[число заражённых COVID-19 в мире превысило 40...
12,11,14,11_началось_прекратил_привело_войне,"[началось, прекратил, привело, войне, отключен...",[На Украине началось телевещание в формате HDT...
13,12,2,12_одна_крупнейших_крае_мировой,"[одна, крупнейших, крае, мировой, истории, взр...","[наводнение в Приморском крае., взрыв нефтяной..."
14,13,1,13____,"[, , , , , , , , , ]",[.]

In [13]:
sample_docs_per_topic(texts, topics, n_samples=10)

topic -1 | total docs: 509
================================================================================
TOPIC 0 | total docs: 985
================================================================================
1. стрельба в магазине Walmart в Эль-Пасо, штат Техас, США, в результате которой погибли 22 человека и ещё 24 получили ранения.
2. в Афганистане проведена наземная операции против укреплённого района Тора-Бора.
3. Владимир Путин высказался против создания в США национальной системы ПРО.
4. принятие совместного заявления против ядерной войны лидерами России, Китая, США, Великобритании и Франции.
5. Вышел указ президента Азербайджана Ильхама Алиева о деноминации маната.
6. в 8:32 на перегоне между станциями Автозаводская — Павелецкая в сторону центра в Московском метрополитене произошёл террористический акт, в результате которого погибли 42 человека и свыше 250 получили ранения.
7. убийство сыновей Саддама Хусейна Кусея и Удея.
8. В результате взрыва бомбы в колумбийском городе Вильявисенсио 10 человек погибли, 25 получили ранения.
9. взрыв на шахте «Листвяжная», в результате которого погиб 51 человек.
10. Стрельба в парламенте швейцарского кантона Цуг. Вооружённый автоматом и пистолетом мужчина в полицейской форме расстрелял 14 человек — депутатов и членов местного правительства. Спустя несколько минут после начала атаки он бросил в людей гранату. 18 человек получили ранения.

================================================================================
TOPIC 1 | total docs: 1145
================================================================================
1. Марк Карни назначен лидером Либеральной партии Канады и премьер-министром Канады.
2. Идрисса Сек назначен на пост премьер-министра Сенегала (до 21 апреля 2004 года).
3. Луис Парра утверждён на должности спикера Национальной ассамблеи Венесуэлы.
4. в Бахрейне в ходе референдума подавляющее большинство избирателей проголосовало за демократические реформы. 98,4 % избирателей одобрили национальную хартию, предусматривающую преобразование Эмирата в конституционную монархию с парламентом.
5. Сенегальский конституционный референдум.
6. В Литве состоялся первый тур президентских выборов. Во второй тур вышли Валдас Адамкус (35,53 % голосов избирателей) и Роландас Паксас (19,66 % голосов).
7. референдум по статусу Фолклендских островов.
8. Парламентские выборы в Австралии. По предварительным данным, победу одержала оппозиционная коалиция.
9. Второй тур президентских выборов в Литве. Победу одержал действующий президент Гитанас Науседа.
10. Вице-губернатор Калужской области Анатолий Артамонов победил на губернаторских выборах в Калужской области; Евгений Михайлов переизбран губернатором Псковской области.

================================================================================
TOPIC 2 | total docs: 704
================================================================================
1. катастрофа Boeing 737 в Гаване.
2. В Ираке сбит транспортный вертолёт Ми-8. Все девять человек (три члена экипажа и шесть гражданских пассажиров), находившихся на его борту, погибли. Вертолёт, направлявшийся на север от Багдада, сбит реактивной гранатой.
3. столкновение поездов в Индии, погибло 294 человека и более 1000 получили ранения.
4. в ходе ракетных испытаний КНДР ракета Хвасон-12 пролетела над островом Хоккайдо, Япония.
5. с космодрома Байконур стартовал транспортный пилотируемый корабль Союз ТМА-05М. Экипаж старта — Юрий Маленченко, Сунита Уильямс (США) и Акихико Хосидэ (Япония).
6. с космодрома Байконур успешно стартовала ракета-носитель «Союз-ФГ» с межпланетной станцией «Венера Экспресс».
7. старт космического корабля Союз ТМА-10М с международным экипажем к международной космической станции.
8. произошло крушение самолёта Су-27 Минобороны России над акваторией Чёрного моря в 50 км от Феодосии. Пилот пропал без вести.
9. В киевском аэропорту Жуляны произошла авиакатастрофа, погибли 5 человек.
10. Железнодорожная авария ночного экспресса Амстердам-Базель под Кёльном. 9 погибших, 149 раненых.

================================================================================
TOPIC 3 | total docs: 552
================================================================================
1. чемпионат мира по футболу 2010 (Южно-Африканская Республика).
2. 17-й чемпионат мира по водным видам спорта (Будапешт, Венгрия).
3. в Сигулде (Латвия) состоялся чемпионат мира по санному спорту.
4. чемпионат мира по современному пятиборью (Тайвань).
5. В Мадриде (Испания) состоялся Финал Лиги чемпионов УЕФА. Победу одержал миланский Интер.
6. 9-й детский конкурс песни Евровидение (Ереван, Армения). Победила группа Candy из Грузии.
7. в Вэйле и Бивер-Крике (США) состоялся чемпионат мира по горнолыжному спорту.
8. вступление Украины в ВТО.
9. российский нападающий «Атланта Трэшерз» Илья Ковальчук признан лучшим игроком недели в НХЛ.
10. чемпионат мира по тяжёлой атлетике (Хьюстон, США).

================================================================================
TOPIC 4 | total docs: 322
================================================================================
1. Абед Хамид Махмуд арестован в районе Тикрита.
2. саммит лидеров Северной и Южной Корей в пограничном пункте переговоров Пханмунджом.
3. референдум в Венесуэле.
4. в США полиция нашла мёртвой бывшего прокурора штата Виргиния Джессику Абер.
5. Движение за освобождение дельты Нигера заявило, что развернёт «террористическую войну», чтобы «защитить христианство» в Нигерии от атак исламской группировки Боко Харам.
6. в день рождения Т. Шевченко у его памятника в Киеве состоялась очередная демонстрация «Украина без Кучмы», а несколько её членов были задержаны правоохранительными органами. Сразу после этого большинство митингующих отправились в Киевское управление МВД с требованием освободить задержанных возле парка Шевченко. Завершилось шествие возле администрации президента на ул. Банковой массовыми столкновениями между участниками акции и отрядами «Беркута». Демонстрации «УБК» продолжались до апреля.
7. начались протесты на Шри-Ланке.
8. акция протеста у парламента Грузии против принятия закона об иноагентах.
9. Вооружённый мятеж в Узбекистане: захвачена тюрьма города Андижан, на свободе оказались более 4000 заключённых.
10. В Судане произошёл военный переворот, в ходе которого президент Судана Омар аль-Башир, который правил страной 30 лет, отстранён от власти и был помещён под домашний арест после многомесячных протестов;

================================================================================
TOPIC 5 | total docs: 498
================================================================================
1. Слободан Милошевич впервые предстал перед трибуналом.
2. от престола отрёкся король Испании Хуан Карлос I после 39 лет правления.
3. танцор фламенко и цыганский активист Хоакин Кортес стал послом цыган в Европейском союзе.
4. Польша закончила строительство стены на границе с Беларусью, протяжённость которой составила 186,25 километров.
5. В должность премьер-министра Молдовы вступил Павел Филип.
6. В должность премьер-министра Португалии вступил Антониу Кошта.
7. президент Сербии Александр Вучич объявил о роспуске парламента.
8. Президент Вьетнама Нгуен Суан Фук объявил о своей отставке. Обязанности президента стала исполнять Во Тхи Ань Суан.
9. на заседании на Мадейре УЕФА принято окончательное решение по городам Украины, которые будут принимать Чемпионат Европы по футболу 2012.
10. Литва перешла на евро, став 19-м членом еврозоны.

================================================================================
TOPIC 6 | total docs: 117
================================================================================
1. Компания Sun Microsystems выпустила 1-ю версию бесплатного офисного пакета OpenOffice.org.
2. Появилась Windows Server 2019.
3. открылся новый веб-сайт правительства США, объединивший 20 тыс. правительственных сайтов (содержит около 27 миллионов веб-страниц).
4. Стив Джобс представил на Apple Expo в Париже первую Mac OS X Public Beta.
5. запущена сеть криптоплатформы «Ethereum», ставшая впоследствии крупнейшей альтернативой биткойну.
6. Обанкротилась американская компания-разработчик и изготовитель графических процессоров трёхмерной графики и видеокарт 3dfx Interactive.
7. полное отключение разработчиком функций «Adobe Flash Player».
8. Открылась почта Gmail от Google
9. Билл Клинтон стал первым президентом США, посетившим Вьетнам после окончания вьетнамской войны.
10. закончилась расширенная поддержка Windows Embedded 8 и Windows Embedded 8.1.

================================================================================
TOPIC 7 | total docs: 261
================================================================================
1. Нептун сделал ровно один оборот с момента его открытия.
2. вторжение в Ирак войск международной коалиции во главе с США с целью свержения режима Саддама Хусейна.
3. Инаугурация президента Израиля Ицхака Герцога.
4. президент Йемена Абд Раббо Мансур Хади подал в отставку.
5. Израиль, посчитав недействительным соглашение о разделении сил между Израилем и Сирией, ввёл войска в буферную зону между странами-подписантами.
6. Получение компанией «Tesla» разрешения на импорт автомобилей в Израиль.
7. трагедия в Кане: разрушение трёхэтажного жилого дома в Ливане в результате израильской бомбардировки, унёсшее жизни 28 мирных жителей.
8. американские ВВС по приказу президента Джо Байдена нанесли серию авиаударов по территории Сирии. Целью ударов стали склады, принадлежащие группировке «Катаиб Хезболла» и некоторым другим, которые поддерживает Иран.
9. Объединённые Арабские Эмираты запустили космический аппарат «Аль-Амаль» на Марс с японского космодрома «Танэгасима».
10. Для грузоперевозчиков открыт крупнейший аэропорт мира Al Maktoum International в Дубае, для пассажирских лайнеров аэропорт откроется в марте 2011 года.

================================================================================
TOPIC 8 | total docs: 126
================================================================================
1. Вступила в силу новая Конституция Грузии.
2. В России принят закон «Об обороте сельскохозяйственных земель».
3. состоялась свадьба принца Гарри и Меган Маркл в Великобритании.
4. вступил в силу принятый в Грузии Закон об иноагентах.
5. парламент Каталонии одобрил резолюцию о независимости автономной области.
6. Парламент Каталонии принял декларацию о государственном суверенитете региона и праве нации на самоопределение.
7. царь Николай II канонизирован Синодом РПЦ.
8. Дмитрий Медведев подписал указ о создании Агентства по защите интеллектуальной собственности.
9. Венгрия приняла поправку в конституцию, запрещающую продажу земли иностранным гражданам.
10. в Германии вступил в силу закон о зарегистрированных гражданских партнёрствах.

================================================================================
TOPIC 9 | total docs: 99
================================================================================
1. Сенат США преодолел вето Дональда Трампа на законопроект с санкциями против «Северного потока — 2».
2. Принятие 15 пакета санкций против России.
3. в Российской Федерации введён новый вид уголовного наказания — «ограничение свободы».
4. вошла в оборот купюра номиналом в 100 000 белорусских рублей.
5. Стоимость нефти Brent обновила очередной минимум с февраля 2016 года. Цена майских фьючерсов на Brent уменьшается на 12,05 %, до 29,77 доллара за баррель, WTI — на 10,4 %, до 28,7 доллара.
6. США потребовали закрыть генконсульство РФ в Сан-Франциско в течение двух дней, до 2 сентября.
7. Сенат США ратифицировал Договор с Россией о сокращении наступательных вооружений.
8. Илон Маск приобрёл «Twitter» за $44 млрд.
9. Вступил в силу запрет ввоза японских автомобилей в Россию.
10. Вступление в РФ в силу запрета на экспорт необработанного круглого леса и запущена цифровая информационная система отслеживания оборота сырья.

================================================================================
TOPIC 10 | total docs: 86
================================================================================
1. в Мексике с начала года от свиного гриппа погибли более 400 человек.
2. Началось распространение COVID-19;
3. Роберт Тулс стал первым человеком, которому имплантировали портативное искусственное сердце. С этим сердцем Тулс прожил 151 день (ум. 30 ноября 2001).
4. В Нигерии около 60 жителей страны погибли в результате нападения боевиков Боко Харам.
5. Учёные Великобритании, США и Италии официально объявили о начале опытов по клонированию человека.
6. Зарегистрированы первые случаи заболевания COVID-19
7. В Иране из-за распространения фейков новостей о способах лечения коронавируса погибли 300 человек, включая детей от отравления метанолом.
8. на Суматре открыли новый вид орангутана.
9. обнаружен человеческий ген долголетия.
10. началась вспышка болезни Эбола: в результате 28 640 человек заразились и 11 315 погибло.

================================================================================
TOPIC 11 | total docs: 68
================================================================================
1. на телеканале HBO состоялась премьера сериала «Игра престолов».
2. включение в эфир новой радиостанции Юмор FM в Москве на частоте 88.7 FM.
3. прекращена поддержка Paint 3D.
4. закрыт магазин приложений Nokia, он заменён Opera Store.
5. Крупнейший с 2007 года сбой в самых распространённых социальных сетях и мессенджерах («WhatsApp», «Facebook», «Amazon», «Twitter», «Google», «TikTok», «Instagram» и «ВКонтакте»).
6. в России на телеканале ОРТ состоялась премьера телеигры «Русская Рулетка» (ведущий — Валдис Пельш) (выходила до 6 августа 2004 года).
7. В России завершили вещание телеканалы «Fox Kids» и «Fox Kids Play».
8. По решению суда прекращено вещание телеканала ТВ-6.
9. Обанкротилась французская компания-разработчик и издатель компьютерных игр Cryo Interactive.
10. исчерпание запасов IPv4-адресов RIPE NCC, регионального интернет-регистратора Европы.

================================================================================
TOPIC 12 | total docs: 135
================================================================================
1. землетрясение в Мексике магнитудой 7,1 Mw в 49 км к юго-западу от мексиканского города Пуэбла-де-Сарагоса и в 100 км от столицы Мехико. Погибли 370 человек и более 6000 получили ранения.
2. землетрясение в Непале магнитудой 6,4. Погибло 128 человек, более сотни ранены.
3. Наводнение в Киншасе, в результате которого погиб 141 человек.
4. Крупное землетрясение в Пакистане. Погибло 23 человека;
5. в результате сильнейших муссонных дождей в Пакистане и Индии погибли более 230 человек.
6. Роспуск Нидерландских Антильских островов.
7. в Техасе (США) произошло внезапное наводнение из-за проливных дождей, погибли не менее 145 человек.
8. Сумма экономического ущерба от лесных пожаров в Калифорнии достигла $275 млрд.
9. Ураган «Катрина», один из наиболее разрушительных ураганов в истории США. Особенно сильно пострадал Новый Орлеан и его окрестности, которые оказались затоплены. Точное количество жертв на начало сентября неизвестно, но количество пропавших без вести оценивается в цифру около 30 тыс. человек.
10. Землетрясение в национальном парке Денали (Аляска, Соединённые Штаты Америки) магнитудой 7,9 Mw — крупнейшее по силе землетрясение за последние 150 лет.

================================================================================
TOPIC 13 | total docs: 34
================================================================================
1. Начало работы социальной сети Одноклассники.
2. основан сборник интернет-мемов Lurkmore.ru
3. Официальный выпуск вокалоида Хацунэ Мику.
4. окончание поддержки компанией «BlackBerry» своих продуктов.
5. всероссийская сельскохозяйственная перепись.
6. в Лондоне состоялась премьера нового мюзикла Эндрю Ллойда Уэббера, сиквела мюзикла «Призрак Оперы» — «Любовь не умрёт никогда».
7. Основная статья: Февраль 2014 года
8. Инцидент с солёным кренделем: во время просмотра по телевизору матча по американскому футболу в Белом доме президент США Джордж Буш подавился солёным кренделем и на несколько секунд потерял сознание. Случившееся получило широкий общественный резонанс.
9. создан Тю́ркский сове́т
10. обмен Виктора Бута на Бритни Грайнер.

In [14]:
save_topics_barchart(topic_model, out_html="topic_plots/topics_barchart_15_topics.html")
save_documents_scatter(topic_model, texts, topics, out_html="topic_plots/documents_scatter_15_topics.html")