In [2]:
import pandas as pd
import time
from core.spacy_country_recognition import CountryRecognizer

In [3]:
df = pd.read_csv('../data/events/3_countries/2000-2025.csv')

df.head()

,date_start,date_end,event,loc,norm_loc
0,2000-01-01,NaN,Деноминация белорусского рубля;,[],[]
1,2000-01-01,NaN,"В связи с «проблемой-2000», в Иране объявлен н...",['Иране'],['Иран']
2,2000-01-01,NaN,"Вступление в силу закона в Великобритании, сог...",['Великобритании'],['Великобритания']
3,2000-01-02,NaN,крушение украинского сухогруза типа «река-море...,"['Тикси', 'Николаев', 'Камбоджи', 'Туапсе']","['Тикси', 'Николаев', 'Камбоджа', 'Туапсе']"
4,2000-01-03,NaN,Обстрел из гранатомёта территории российского ...,"['Ливане', 'Бейрут']","['Ливана', 'Бейрут']"

In [4]:
recognizer = CountryRecognizer()

start = time.time()
df["country"] = recognizer.match_locations_series(df["event"])
elapsed = time.time() - start

recognized = df["country"].notna().sum()
print(f"Время:     {elapsed:.2f} с")
print(f"Опознано:  {recognized} / {len(df)} строк ({recognized / len(df) * 100:.1f}%)")
df.head(10)

Время:     30.13 с
Опознано:  3900 / 5630 строк (69.3%)

,date_start,date_end,event,loc,norm_loc,country
0,2000-01-01,NaN,Деноминация белорусского рубля;,[],[],[BELARUS]
1,2000-01-01,NaN,"В связи с «проблемой-2000», в Иране объявлен н...",['Иране'],['Иран'],[IRAN]
2,2000-01-01,NaN,"Вступление в силу закона в Великобритании, сог...",['Великобритании'],['Великобритания'],[UK]
3,2000-01-02,NaN,крушение украинского сухогруза типа «река-море...,"['Тикси', 'Николаев', 'Камбоджи', 'Туапсе']","['Тикси', 'Николаев', 'Камбоджа', 'Туапсе']","[UKRAINE, CAMBODIA]"
4,2000-01-03,NaN,Обстрел из гранатомёта территории российского ...,"['Ливане', 'Бейрут']","['Ливана', 'Бейрут']",[RUSSIA]
5,2000-01-03,NaN,Победа коалиции социал-демократов-социал-либер...,['Хорватии'],['Хорватия'],[CROATIA]
6,2000-01-08,NaN,первая Рождественская литургия в Храме Христа ...,"['Московский', 'Руси']","['Московский', 'Русь']",[RUSSIA]
7,2000-01-09,NaN,Переизбрание Ислама Каримова президентом Респу...,['Республики Узбекистан'],['Республика Узбекистан'],[UZBEKISTAN]
8,2000-01-09,NaN,Проведение в трёх субъектах России повторных в...,"['России', 'Московской', 'Тверской', 'Новосиби...","['Россия', 'Московская', 'Тверская', 'Новосиби...",[RUSSIA]
9,2000-01-09,NaN,Вторая чеченская война: прорыв боевиков в Шали...,"['Шали', 'Аргун', 'Шали', 'Аргуном']","['Шаль', 'Аргун']",[RUSSIA]