In [34]:
import re

import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('../data/events/2_struct/2000-2025.csv')

df.head()

   date_start date_end                                              event
0  2000-01-01      NaN                    Деноминация белорусского рубля;
1  2000-01-01      NaN  В связи с «проблемой-2000», в Иране объявлен н...
2  2000-01-01      NaN  Вступление в силу закона в Великобритании, сог...
3  2000-01-02      NaN  крушение украинского сухогруза типа «река-море...
4  2000-01-03      NaN  Обстрел из гранатомёта территории российского ...

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5645 entries, 0 to 5644
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date_start  5645 non-null   object
 1   date_end    603 non-null    object
 2   event       5645 non-null   object
dtypes: object(3)
memory usage: 132.4+ KB

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

ru_stopwords = stopwords.words("russian")


def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"[^а-яё\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


texts = df["event"].dropna().astype(str).apply(clean_text)

vectorizer = TfidfVectorizer(
    max_df=0.9,
    min_df=5,
    stop_words=ru_stopwords,
    ngram_range=(1, 3),
    sublinear_tf=True,
)
X = vectorizer.fit_transform(texts)

n_topics = 10
model = NMF(n_components=n_topics, random_state=42)
W = model.fit_transform(X)
H = model.components_

feature_names = vectorizer.get_feature_names_out()
topics = {}
for i, topic in enumerate(H):
    top_words = [feature_names[j] for j in topic.argsort()[:-11:-1]]
    topics[f"Topic {i + 1}"] = top_words

print(len(vectorizer.vocabulary_))
topics

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ruslan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

3311

{'Topic 1': ['парламентские выборы',
  'парламентские',
  'выборы',
  'досрочные парламентские',
  'досрочные парламентские выборы',
  'досрочные',
  'партия',
  'большинство',
  'сирии',
  'мест'],
 'Topic 2': ['человек',
  'погибли',
  'погибли человек',
  'результате',
  'человека',
  'человек погибли',
  'получили',
  'ранены',
  'ранения',
  'погибло'],
 'Topic 3': ['должность',
  'вступил',
  'должность президента',
  'президента',
  'вступил должность',
  'вступил должность президента',
  'года',
  'президент',
  'должность президент',
  'вступил должность президент'],
 'Topic 4': ['тур',
  'выборов',
  'президентских',
  'президентских выборов',
  'второй',
  'второй тур',
  'тур президентских',
  'тур президентских выборов',
  'второй тур президентских',
  'одержал'],
 'Topic 5': ['мира',
  'чемпионат',
  'чемпионат мира',
  'россия',
  'мира хоккею',
  'хоккею',
  'чемпионат мира хоккею',
  'сборная',
  'мира хоккею шайбой',
  'хоккею шайбой'],
 'Topic 6': ['премьер',
  'министром',
  'премьер министром',
  'стал',
  'новым',
  'новым премьер министром',
  'новым премьер',
  'министра',
  'премьер министра',
  'назначен'],
 'Topic 7': ['сша',
  'союз',
  'корабля',
  'экипаж',
  'корабля союз',
  'тма',
  'союз тма',
  'космического',
  'космического корабля',
  'космического корабля союз'],
 'Topic 8': ['президентские',
  'президентские выборы',
  'выборы',
  'одержал',
  'победу одержал',
  'победу',
  'президент',
  'действующий',
  'действующий президент',
  'избран'],
 'Topic 9': ['россии',
  'день',
  'единый',
  'голосования',
  'против',
  'единый день голосования',
  'единый день',
  'день голосования',
  'голосования россии',
  'день голосования россии'],
 'Topic 10': ['одержала',
  'победу',
  'победу одержала',
  'партия',
  'правящая',
  'парламентских',
  'сборная',
  'одержала правящая',
  'победу одержала правящая',
  'оппозиционная']}

In [38]:
from sklearn.decomposition import TruncatedSVD

n_topics = 10

lsa = TruncatedSVD(
    n_components=n_topics,
    random_state=42
)

X_lsa = lsa.fit_transform(X)
feature_names = vectorizer.get_feature_names_out()

topics = {}

for i, comp in enumerate(lsa.components_):
    indices = np.argsort(np.abs(comp))[-12:]
    top_words = [feature_names[j] for j in indices]
    topics[f"Topic {i + 1}"] = top_words

topics

{'Topic 1': ['тур',
  'победу одержала',
  'победу одержал',
  'одержал',
  'одержала',
  'партия',
  'президентские выборы',
  'президентские',
  'победу',
  'парламентские выборы',
  'парламентские',
  'выборы'],
 'Topic 2': ['президента',
  'погибло',
  'получили ранения',
  'ранены',
  'ранения',
  'получили',
  'человек погибли',
  'человека',
  'результате',
  'погибли человек',
  'погибли',
  'человек'],
 'Topic 3': ['одержал',
  'погибли',
  'человек',
  'тур',
  'выборов',
  'парламентские',
  'парламентские выборы',
  'вступил должность',
  'должность президента',
  'вступил',
  'президента',
  'должность'],
 'Topic 4': ['одержал',
  'победу',
  'второй',
  'президентских выборов',
  'второй тур',
  'президентских',
  'вступил должность',
  'должность президента',
  'выборов',
  'тур',
  'вступил',
  'должность'],
 'Topic 5': ['хоккею шайбой',
  'мира хоккею шайбой',
  'шайбой',
  'одержала',
  'чемпионат мира хоккею',
  'хоккею',
  'мира хоккею',
  'сборная',
  'россия',
  'чемпионат мира',
  'чемпионат',
  'мира'],
 'Topic 6': ['министра',
  'президента',
  'вступил',
  'должность',
  'должность президента',
  'новым премьер',
  'новым премьер министром',
  'новым',
  'стал',
  'премьер министром',
  'министром',
  'премьер'],
 'Topic 7': ['союз тма экипаж',
  'корабля союз тма',
  'космического корабля союз',
  'космического корабля',
  'космического',
  'союз тма',
  'тма',
  'корабля союз',
  'экипаж',
  'корабля',
  'союз',
  'сша'],
 'Topic 8': ['тур президентских',
  'победу одержал',
  'одержал',
  'тур',
  'президентских',
  'президентских выборов',
  'выборов',
  'выборы',
  'парламентские',
  'парламентские выборы',
  'президентские',
  'президентские выборы'],
 'Topic 9': ['день голосования россии',
  'президентские',
  'президентские выборы',
  'президент',
  'против',
  'день голосования',
  'единый день',
  'единый день голосования',
  'голосования',
  'единый',
  'день',
  'россии'],
 'Topic 10': ['выборы',
  'первый',
  'тур',
  'президента',
  'победу одержал',
  'одержал',
  'партия',
  'президентские',
  'президентские выборы',
  'победу одержала',
  'одержала',
  'победу']}

In [39]:
from sklearn.decomposition import LatentDirichletAllocation

n_topics = 10
lda = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    learning_method="batch",
    max_iter=30,
    doc_topic_prior=0.1,  # alpha
    topic_word_prior=0.01  # beta
)
X_lda = lda.fit_transform(X)

feature_names = vectorizer.get_feature_names_out()
topics = {}
for i, topic_dist in enumerate(lda.components_):
    top_idx = topic_dist.argsort()[-12:][::-1]
    topics[f"Topic {i + 1}"] = [feature_names[j] for j in top_idx]

topics

{'Topic 1': ['стал',
  'министром',
  'премьер министром',
  'премьер',
  'новым',
  'референдум',
  'сша',
  'президентом',
  'новым премьер',
  'новым премьер министром',
  'великобритании',
  'конституционный'],
 'Topic 2': ['космический',
  'союз',
  'россии',
  'рф',
  'союз тма',
  'тма',
  'корабль',
  'аппарат',
  'посадки',
  'сша',
  'казахстане',
  'представителей'],
 'Topic 3': ['россия',
  'впервые',
  'сша',
  'европы',
  'станции',
  'истории',
  'второй тур выборов',
  'тур выборов',
  'старт',
  'выборов президента',
  'полёт',
  'оон'],
 'Topic 4': ['человек',
  'погибли',
  'результате',
  'погибли человек',
  'человека',
  'погибло',
  'ранены',
  'получили',
  'человек погибли',
  'ранения',
  'взрыв',
  'получили ранения'],
 'Topic 5': ['парламентские выборы',
  'парламентские',
  'выборы',
  'премьер',
  'президент',
  'министра',
  'премьер министра',
  'года',
  'должность',
  'министр',
  'вступил',
  'отставку'],
 'Topic 6': ['сша',
  'корабля',
  'россии',
  'космического',
  'ес',
  'первый',
  'космического корабля',
  'союз',
  'населения',
  'вышли',
  'мкс',
  'владимира'],
 'Topic 7': ['выборы',
  'победу',
  'выборов',
  'президентские',
  'тур',
  'президентские выборы',
  'одержал',
  'партия',
  'победу одержал',
  'парламентские',
  'парламентские выборы',
  'второй'],
 'Topic 8': ['мира',
  'чемпионат',
  'чемпионат мира',
  'саммит',
  'россии',
  'сборная',
  'открыт',
  'компания',
  'германия',
  'обязанности',
  'россия',
  'мира хоккею'],
 'Topic 9': ['землетрясение',
  'убийство',
  'магнитудой',
  'российской',
  'отношения',
  'федерации',
  'дипломатические',
  'дипломатические отношения',
  'беспорядки',
  'российской федерации',
  'произошло',
  'массовые'],
 'Topic 10': ['президента',
  'должность',
  'должность президента',
  'вступил',
  'вступил должность',
  'вступил должность президента',
  'международный',
  'официально',
  'республики',
  'вступила',
  'нато',
  'кинофестиваль']}

In [40]:
import os
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

texts = df["event"]

embedding_model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

vectorizer_model = CountVectorizer(
    ngram_range=(1, 3),
    min_df=5
)

MODEL_PATH = "../models/bertopic_events_auto"

if os.path.exists(MODEL_PATH):
    topic_model = BERTopic.load(MODEL_PATH, embedding_model=embedding_model)
    topics = topic_model.topics_
    print(f"Модель загружена из {MODEL_PATH}")
else:
    topic_model = BERTopic(
        embedding_model=embedding_model,
        vectorizer_model=vectorizer_model,
        language="multilingual",
        calculate_probabilities=True,
        verbose=True,
    )
    topics, probs = topic_model.fit_transform(texts)
    topic_model.save(MODEL_PATH)
    print(f"Модель обучена и сохранена в {MODEL_PATH}")

Модель загружена из ../models/bertopic_events_auto

In [41]:
import random
import socket
import uuid
from collections import defaultdict

from dash import Dash, html, dcc


def _find_free_port(min_port=10001):
    port = min_port
    while True:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex(("localhost", port)) != 0:
                return port
        port += 1


def serve_figure(fig, title=""):
    """Запускает Dash-сервер для отображения Plotly-фигуры. Выводит ссылку в консоль."""
    app = Dash(f"fig_{uuid.uuid4().hex[:8]}")
    app.layout = html.Div([dcc.Graph(figure=fig)])
    port = _find_free_port()
    app.run(port=port, jupyter_mode="external")


def sample_docs_per_topic(texts, topics, n_samples=10, seed=42):
    random.seed(seed)

    topic_to_docs = defaultdict(list)
    for text, topic in zip(texts, topics):
        topic_to_docs[topic].append(text)

    for topic_id, docs in sorted(topic_to_docs.items()):
        if topic_id == -1:
            print(f"topic {topic_id} | total docs: {len(docs)}")
            continue

        print("=" * 80)
        print(f"TOPIC {topic_id} | total docs: {len(docs)}")
        print("=" * 80)

        sampled = random.sample(docs, min(n_samples, len(docs)))
        for i, doc in enumerate(sampled, 1):
            print(f"{i}. {doc}")
        print()


def visualize_topics_barchart(topic_model, top_n_topics=30):
    fig = topic_model.visualize_barchart(top_n_topics=top_n_topics, n_words=10)
    serve_figure(fig, "Barchart:")


def visualize_documents_scatter(topic_model, texts, topics):
    fig = topic_model.visualize_documents(docs=texts, topics=topics)
    serve_figure(fig, "Scatter:")

In [42]:
print('=== Auto-модель: scatter документов по темам ===')
visualize_documents_scatter(topic_model, texts, topics)

=== Auto-модель: scatter документов по темам ===
Dash app running on http://127.0.0.1:10011/

In [43]:
topic_model.get_topic_info().head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1527,-1_на_тур_премьер_по,"[на, тур, премьер, по, парламентские выборы, ч...",[второй тур президентских выборов в Иране. Поб...
1,0,188,0_перу_всеобщие_чили_всеобщие выборы,"[перу, всеобщие, чили, всеобщие выборы, презид...",[Второй тур президентских выборов в Уругвае. П...
2,1,139,1_протеста_против_протесты_массовые,"[протеста, против, протесты, массовые, началис...",[в Армении начались протесты против уступок по...
3,2,89,2_результате взрыва_взрыва_результате_погибли,"[результате взрыва, взрыва, результате, погибл...",[В результате взрыва на химическом заводе во ф...
4,3,87,3_сша_президент сша_трампа_дональда трампа,"[сша, президент сша, трампа, дональда трампа, ...",[Коллегия выборщиков утвердила победу Дональда...
5,4,87,4_выборы_всеобщие выборы_всеобщие_президентские,"[выборы, всеобщие выборы, всеобщие, президентс...",[Президентские выборы в Кот-д’Ивуаре. Победу о...
6,5,86,5_самолёт_авиакомпании_борту_на борту,"[самолёт, авиакомпании, борту, на борту, все, ...",[Под Далянем разбился авиалайнер McDonnell Dou...
7,6,80,6_произошло_землетрясения_человек_более,"[произошло, землетрясения, человек, более, без...",[В Тбилиси произошло землетрясение магнитудой ...
8,7,73,7_австрии_германии_парламентские выборы_партия,"[австрии, германии, парламентские выборы, парт...",[Парламентские выборы в Австрии. По предварите...
9,8,71,8_саммит_нато_государств_брикс,"[саммит, нато, государств, брикс, глав, снг, г...","[саммит АТЭС (Манила, Филиппины)., саммит ШОС ..."

In [44]:
sample_docs_per_topic(texts, topics, n_samples=10)
print('=== Auto-модель: barchart тем ===')
visualize_topics_barchart(topic_model)

topic -1 | total docs: 1527
================================================================================
TOPIC 0 | total docs: 188
================================================================================
1. президент Эквадора Даниэль Нобоа ввёл чрезвычайное положение в стране после побега из тюрьмы строгого режима одного из лидеров наркокартеля «Лос Чонерос» и начала вооружённых столкновений между правительством и наркокартелями.
2. в Венесуэле совершена попытка государственного переворота. Свергнут президент Уго Чавес, распущены парламент и Верховный суд. Временным президентом стал Педро Кармона. На следующий день Чавес восстановлен в должности, а Кармона арестован.
3. Альберто Фухимори переизбран президентом Перу. Оппозиция не признала выборы и ответила новыми маршами протеста, в которых участвовали сотни тысяч людей. Полиция жестоко подавляла выступления. В ходе столкновений сотни людей были ранены и арестованы.
4. выборы президента Венесуэлы. Победу одержал Уго Чавес.
5. VI-й съезд Коммунистической партии Кубы принял решение о серьёзных политических и экономических реформах в стране.
6. на очередных президентских выборах в Панаме победу одержал представитель оппозиционной партии, 57-летний владелец сети супермаркетов Рикардо Мартинелли. Действующий президент Мартин Торрихос не мог участвовать в выборах ввиду того, что конституция ограничивает период президентства одним сроком.
7. Международный валютный фонд одобрил выделение Бразилии займа в размере $30,4 миллиарда долларов с целью предотвращения спада экономики этой страны.
8. В Коста-Рике прошли всеобщие выборы: первый тур президентских выборов и выборы в парламент. Большинство мест в парламенте получил Социально-христианский союз. Во второй тур президентских выборов вышли Абель Пачеко (38,6 %) и Роландо Арайя Монге (31,1 %).
9. В Венесуэле начались акции протеста в связи с переизбранием Николаса Мадуро на пост президента страны.
10. Рауль Кастро покинул пост первого секретаря Коммунистической партии Кубы.

================================================================================
TOPIC 1 | total docs: 139
================================================================================
1. массовые протесты в исламском мире против публикации карикатур на пророка Мухаммеда (Карикатурный скандал 2005—2006 годов).
2. В России прошли антивоенные митинги против мобилизации.
3. в Цинциннати произошли массовые беспорядки в связи с убийством 19-летнего афроамериканца белым полицейским .
4. на Пушкинской площади прошёл митинг в защиту свободы слова и телекомпании НТВ, организованный партией «Яблоко», СПС и Союзом журналистов России. В нём приняли участие 20 тыс. человек.
5. массовые демонстрации в Катманду и других городах Непала. Протестующие выступали за отмену монархии и установление парламентской республики в стране. Против демонстрантов в столице полицией было применено оружие, что повлекло многочисленные жертвы.
6. Массовые митинги в Испании с требованием упразднения монархии и введения республиканской формы правления.
7. в Венгрии прошли протесты нелегальных мигрантов, требующих предоставить им поезда в Германию.
8. Митинги в Грузии с требованием роспуска парламента и назначения новых выборов, а также против отмены курса Грузии на евроинтеграцию.
9. в день рождения Т. Шевченко у его памятника в Киеве состоялась очередная демонстрация «Украина без Кучмы», а несколько её членов были задержаны правоохранительными органами. Сразу после этого большинство митингующих отправились в Киевское управление МВД с требованием освободить задержанных возле парка Шевченко. Завершилось шествие возле администрации президента на ул. Банковой массовыми столкновениями между участниками акции и отрядами «Беркута». Демонстрации «УБК» продолжались до апреля.
10. антиправительственный мятеж в Центральноафриканской Республике с требованием отставки президента страны Франсуа Бозизе.

================================================================================
TOPIC 2 | total docs: 89
================================================================================
1. Взрыв на территории Загорского оптико-механического завода: погиб 1 человек, 8 пропали без вести, более 80 пострадали. Повреждены 92 многоквартирных дома, 30 частных и садовых домов, суд, 2 школы, спорткомплекс, 13 магазинов и 3 производственно-складских помещения.
2. теракты в Барселоне и Камбрильсе (Испания). Погибли 16 человек, более 120 получили ранения.
3. теракты в Норвегии. В результате взрыва в Осло около здания норвежского правительства 8 человек погибли, десятки ранены. В результате нападения на молодёжный лагерь на острове Утёйа погибли 68 и десятки получили ранения.
4. В результате взрыва бомбы в универмаге финского города Вантаа 7 человек погибли, 10 получили ранения.
5. авария на руднике и образование провала в Соликамске.
6. в Вене произошли теракты. 5 человек погибли, 23 получили ранения.
7. в результате взрыва пиротехники на рынке в Бишкеке 5 человек погибли, около 40 получили ранения).
8. При взрыве в шахте «Баракова» в Краснодоне погиб 81 шахтёр. Самые тяжёлые последствия от аварии на Украине за 20 лет.
9. В результате взрыва в мечети пакистанского города Бхаккар погибли 11 человек.
10. Серия взрывов в Днепропетровске (Украина). Пострадали 29 человек.

================================================================================
TOPIC 3 | total docs: 87
================================================================================
1. президент США Дональд Трамп подписал законопроект CAATSA, законодательно закрепляющий и расширяющий санкции против России, Ирана и КНДР.
2. Барак Обама вступил в должность президента США на второй срок.
3. президент США Дж. Буш декларировал необходимость быть независимым от импортной нефти.
4. Бараку Обаме присудили Нобелевскую премию мира.
5. Джордж Буш объявил об окончании основных боевых действий в Ираке.
6. Президент США Джордж Буш объявил о намерении Соединённых Штатов снова стать членом ЮНЕСКО, из состава которой они вышли 18 лет назад (США восстановлены в ЮНЕСКО 29 сентября 2003 года).
7. Бывший мэр Нью-Йорка и мультимиллиардер Майкл Блумберг официально объявил о решении участвовать в борьбе за выдвижение кандидатом в президенты США от Демократической партии;
8. Конгресс США принял резолюцию, разрешившую ведение боевых действий против Ирака.
9. промежуточные выборы сенаторов США.
10. Джина Хаспел стала первой в истории женщиной-главой ЦРУ США.

================================================================================
TOPIC 4 | total docs: 87
================================================================================
1. Парламентские выборы в Ботсване. Правящая партия ДПБ отстранена от власти, что положило конец 58-летнему непрерывному правлению. Дума Боко из партии UDC избран президентом Ботсваны.
2. премьер-министром Лесото вновь стал Бетуэль Пакалита Мосисили.
3. Йовери Кагута Мусевени переизбран президентом Уганды.
4. второй тур президентских выборов в Либерии. Победу одержал Джордж Веа.
5. Проведение президентских выборов в Чаде.
6. в Гаити прошёл второй тур президентских выборов. Новым президентом Гаити стал Мишель Мартейи.
7. Парламентские выборы в Лаосе.
8. парламентские выборы в Лаосе. НРПЛ одержала победу, получив все 109 мест. Явка избирателей составила 99,9 %.
9. парламентские и президентские выборы в Нигерии.
10. парламентские выборы в Республике Гаити.

================================================================================
TOPIC 5 | total docs: 86
================================================================================
1. авиакатастрофа Ан-12БК под Кавалой. Погибло 8 человек.
2. катастрофа Boeing 737 в Тэнсяне (Китай). Погибли все 132 человека на борту.
3. В Мадриде потерпел крушение пассажирский самолёт McDonnell Douglas MD-82. Из 172 человек, находившихся на борту, 154 человека погибло.
4. В Нидерландах начался суд по делу о крушении Boeing MH17.
5. Катастрофа самолёта «Як-42» под Трабзоном, погибло 75 человек: 62 испанских военнослужащих и 13 членов экипажа.
6. авиакомпания Sabena признана банкротом.
7. в Воронежской области при выполнении авиационно-химических работ потерпел катастрофу самолёт Авиатика-МАИ-890. Пилот погиб.
8. Катастрофа медицинского транспортного самолёта Learjet 55 в Филадельфии. В результате все 6 человек на борту погибли. На земле погиб один человек, 24 пострадали.
9. В Тегеранском аэропорту «Мехрабад» совершил аварийную посадку самолёт Боинг-707. 3 человека погибли и десятки получили ранения. Во время совершения посадки при соприкосновении со взлётно-посадочной полосой разорвалась и загорелась резина шасси, загорелся левый двигатель, сам самолёт выехал с полосы посадки в сторону близлежащей речки, сильно пострадал корпус авиалайнера.
10. в 2.15 по московскому времени в районе Сочи разбился пассажирский самолёт А-320 армянской авиакомпании «Армавиа», выполнявший рейс Ереван—Сочи. Все 113 человек, находившиеся на борту, погибли. Самолёт, выполняя заход на посадку в сложных метеоусловиях, упал в море.

================================================================================
TOPIC 6 | total docs: 80
================================================================================
1. в Пакистане произошло землетрясение с магнитудой 7,6 по шкале Рихтера. Оно стало самым сильным за всё время сейсмических наблюдений в Южной Азии. По официальным данным, погибли более 73 тысячи человек, в их числе 17 тысяч детей. По некоторым оценкам, число погибших составило более 100 тысяч человек. Более трёх миллионов пакистанцев остались без крова.
2. Землетрясение в иранской провинции Бушир магнитудой 6,3. Погибли 37 человек, около 850 получили ранения.
3. Новое землетрясение магнитудой 5,7 баллов по шкале Рихтера произошло в китайской провинции Сычуань.
4. землетрясение магнитудой 6,4 в Албании, погиб 51 человек.
5. в Непале и Индии произошло повторное землетрясение магнитудой 7,4. В Непале погибли 117 человек, ещё 1926 пострадали; в Индии погибли 17 человек, ещё один человек погиб на территории Китая.
6. землетрясение в Афганистане. Не менее 1000 человек погибли, и 1500 получили ранения.
7. Землетрясение и цунами на Сулавеси, Индонезия. По меньшей мере 4340 человек погибло и 10 679 человек получили ранения.
8. В результате разрушительного землетрясения в Крайстчерче (Новая Зеландия) магнитудой 6,3 погибли 166 человек, 122 — пропали без вести.
9. цунами в Зондском проливе, вызванное извержением вулкана Анак-Кракатау; 437 человек погибли.
10. землетрясение в Папуа-Новой Гвинее магнитудой 7,5 баллов. Погиб 31 человек, ещё более 300 получили ранения.

================================================================================
TOPIC 7 | total docs: 73
================================================================================
1. Парламентские выборы в Норвегии. Победу одержала коалиция правых партий.
2. Парламентские выборы в Швеции. По предварительным итогам победу одержала оппозиционная Социал-демократическая партия Швеции.
3. в Нидерландах состоялись внеочередные парламентские выборы, принёсшие победу правящей партии Христианско-демократический призыв.
4. Досрочные парламентские выборы в Португалии. Победила оппозиционная Социал-демократическая партия. Премьер-министр Жозе Сократеш подал в отставку.
5. Президент ФРГ Франк-Вальтер Штайнмайер распустил парламент и назначил досрочные парламентские выборы.
6. Новым президентом Швейцарии стал Дидье Буркхальтер.
7. на внеочередных выборах президентом Германии избран Кристиан Вульф.
8. Ангела Меркель окончательно сложила свои полномочия. Новым федеральным канцлером Германии был назначен Олаф Шольц.
9. Парламентские выборы в Швеции.
10. Внеочередные парламентские выборы в Португалии.

================================================================================
TOPIC 8 | total docs: 71
================================================================================
1. саммит G-20 в Брисбене (Австралия).
2. саммит G20 (Гамбург, Германия).
3. Саммит глав СНГ в Казани.
4. саммит G7 в замке Эльмау (Бавария, Германия).
5. в Шарм-эш-Шейхе (Египет) прошла международная конференция по Ираку. В ней участвовали главы МИД 20 стран, а также представители нескольких международных организаций. На повестке дня — обсуждение текущей ситуации в Ираке и послевоенного обустройства этой страны.
6. саммит G7 в Италии.
7. В Брюсселе состоялся внеочередной саммит НАТО.
8. встреча глав государств-членов ШОС в Ташкенте.
9. проведение XX Международного ботанического конгресса в Мадриде (Испания).
10. саммит G20.

================================================================================
TOPIC 9 | total docs: 68
================================================================================
1. Вторая чеченская война: вертолёт Ми-8МТ ВС РФ был сбит из ПЗРК возле Ханкалы. 9 человек погибли.
2. Вторая чеченская война: при перелёте из Северной Осетии в Ингушетию потерпел катастрофу, врезавшись в гору, вертолёт МИ-8. Все находившиеся на его борту 12 человек погибли.
3. В Сирии погиб российский экипаж боевого вертолёта Ми-25 в составе: Ряфагать Хабибулин и Евгений Долгин. Командованием российские военные лётчики представлены к государственным наградам.
4. Вторая чеченская война: вооружённое нападение чеченских и ингушских боевиков на Ингушетию.
5. произошла авиакатастрофа под Смоленском. В авиакатастрофе погибли президент Польши Лех Качиньский с супругой, глава Генштаба Польши Франтишек Гонгор, глава Национального банка Польши Славомир Скшипек и др.
6. Вторая чеченская война: в результате серии терактов с использованием заминированных грузовиков погибло более 30 милиционеров и военнослужащих федеральных сил;
7. Вторая чеченская война: женщина-смертница (вдова погибшего боевика) подорвала себя на центральной площади Урус-Мартана (Чечня), когда там находился комендант района генерал-майор Гейдар Гаджиев. Гаджиев погиб, трое охранников ранены.
8. Убит Любиша Савич, бывший командир Первой биелинской легкопехотной гвардейской бригады «пантеры» республики Сербской.
9. нападение грузинских боевиков под руководством Эмзара Квициани при поддержке чеченских боевиков полевого командира Руслана Гелаева в Кодорском ущелье в ходе грузино-абхазского конфликта.
10. в ходе перестрелки с пограничниками смертельно ранен полевой командир чеченских террористов Руслан Гелаев.

================================================================================
TOPIC 10 | total docs: 67
================================================================================
1. Стрельба в Лас-Вегасе.
2. стрельба в гимназии № 5 в Брянске, погибло два человека (в том числе нападавшая) и пятеро ранены.
3. стрельба в Монтерей-Парке (США). Погибли 10 человек, ещё 10 получили ранения.
4. Массовое убийство в Пермском государственном университете. Погибло 6 человек, 43 пострадали;
5. в супермаркете в центре Стокгольма на министра иностранных дел Швеции Анну Линд совершено покушение. Нападавший нанёс ей несколько ударов ножом, после чего скрылся. Линд доставлена в Каролинскую больницу, где врачи на протяжении нескольких часов боролись за её жизнь. Однако ранним утром 11 сентября она скончалась от полученных травм.
6. Стрельба в парламенте швейцарского кантона Цуг. Вооружённый автоматом и пистолетом мужчина в полицейской форме расстрелял 14 человек — депутатов и членов местного правительства. Спустя несколько минут после начала атаки он бросил в людей гранату. 18 человек получили ранения.
7. Гибель 14 школьников на Сямозере (Карелия).
8. Массовое убийство в гей-клубе в Орландо стало крупнейшим по числу жертв. 49 погибших 50 ранено
9. американская актриса, фотомодель и певица Бонни Ли Бакли была убита выстрелом в голову. Первоначально в её убийстве был обвинён супруг Бакли актёр Роберт Блейк, однако 16 марта 2005 года он был признан невиновным. Убийство осталось нераскрытым.
10. Массовое убийство в Уокешо. Подозреваемый въехал на внедорожнике в толпу людей. 5 человек погибло, не менее 48 ранены;

================================================================================
TOPIC 11 | total docs: 64
================================================================================
1. Приземление корабля Союз ТМ-32. Экипаж посадки — В. М. Афанасьев, К. М. Козеев и К. Эньере (Франция).
2. с космодрома Байконур стартовал космический корабль Союз ТМА-16М для годичного пребывания в космосе. Состав экипажа — Геннадий Падалка, Михаил Корниенко и Скотт Келли.
3. Старт космического корабля Союз ТМ-34, последний полёт корабля модификации ТМ. Экипаж старта — Юрий Гидзенко, Роберто Виттори (Италия) и Марк Шаттлуорт (ЮАР). Шаттлуорт — первый астронавт из ЮАР.
4. старт космического корабля «Союз ТМА-2». Экипаж старта — Юрий Маленченко и Эдвард Цзан Лу (США).
5. с космодрома Байконур запущен космический корабль Союз ТМА-21 «Юрий Гагарин». Экипаж старта — Андрей Борисенко, Александр Самокутяев и Рональд Гаран (США).
6. приземление корабля «Союз ТМА-1». Экипаж посадки — Николай Бударин, Кеннет Бауэрсокс (США) и Доналд Петтит (США).
7. приземление космического корабля Союз ТМА-04М. Экипаж приземления — Геннадий Падалка, Сергей Ревин и гражданин США Джозеф Акаба.
8. с космодрома Байконур запущен Союз ТМА-22 к МКС. Экипаж старта — Антон Шкаплеров, Анатолий Иванишин, Дэниел Бёрбэнк (США). Последний запуск корабля модификации ТМА.
9. приземление космического корабля Союз ТМА-12. Экипаж посадки — С. А. Волков, О. Д. Кононенко и Р. Гэрриот (США).
10. Роскосмос запустил с космодрома Байконур Союз ТМА-20. Экипаж старта — Дмитрий Кондратьев, Катерина Коулман (США) и Паоло Несполи (Италия).

================================================================================
TOPIC 12 | total docs: 63
================================================================================
1. Марсоход «Спирит» (MER-A) успешно спустился на поверхность Марса.
2. стартовал основной этап проекта Марс-500 — серия экспериментов по длительной изоляции экипажа в условиях специально созданного наземного экспериментального комплекса.
3. запуск Европейским космическим агентством космического аппарата «JUICE», предназначенного для исследования спутников Юпитера.
4. на орбиту выведен космический телескоп Gaia.
5. Нептун сделал ровно один оборот с момента его открытия.
6. косморобот Curiosity совершил посадку на Марс в районе кратера Гейла.
7. открытие планеты Глизе 581c.
8. в США запущен спутник IRIS, предназначенный для изучения Солнца в инфракрасном диапазоне.
9. В пустыне на севере штата Аризона прошли успешные испытания прототипов марсохода «Spirit».
10. космический аппарат НАСА «Новые горизонты» прошёл мимо Плутона.

================================================================================
TOPIC 13 | total docs: 62
================================================================================
1. Парламент Ирана назвал Пентагон террористической организацией, а также всех командиров, агентов и иных лиц, причастных к смерти генерала Касема Сулеймани. Фактически вся армия США была объявлена парламентом Ирана «террористической организацией».
2. Войска коалиции заняли Киркук.
3. министр внутренних дел Турции Сулейман Сойлу заявил, что 11 ноября Турция начнёт экстрадицию арестованных боевиков Исламского государства в страны их происхождения.
4. Повстанцы в Сирии захватили город Алеппо.
5. авиаудар крылатыми ракетами «Томагавк» по сирийской авиабазе «Эш-Шайрат» в провинции Хомс, нанесённый после химической атаки в Идлибе.
6. американские ВВС по приказу президента Джо Байдена нанесли серию авиаударов по территории Сирии. Целью ударов стали склады, принадлежащие группировке «Катаиб Хезболла» и некоторым другим, которые поддерживает Иран.
7. создана террористическая организация «Исламское государство».
8. начало гражданской войны в Мьянме.
9. Турция начала военную операцию «Источник мира» на территории Сирии.
10. В Багдаде ракета поразила штаб политической партии Высший исламский совет Ирака.

================================================================================
TOPIC 14 | total docs: 59

In [45]:
import os

MODEL_PATH_15 = "../models/bertopic_events_15topics"

if os.path.exists(MODEL_PATH_15):
    topic_model = BERTopic.load(MODEL_PATH_15, embedding_model=embedding_model)
    topics = topic_model.topics_
    print(f"Модель загружена из {MODEL_PATH_15}")
else:
    topic_model = BERTopic(
        embedding_model=embedding_model,
        vectorizer_model=vectorizer_model,
        language="multilingual",
        calculate_probabilities=True,
        verbose=True,
        zeroshot_topic_list=[
            "природные катаклизмы", "авиакатастрофы", "террористические нападения", "техногенные аварии", "войны",
            "санкции", "выборы", "нефть", "крипт"
        ],
        seed_topic_list=[
            ["землетрясение", "цунами", "извержение вулкана", "тайфун", "ураган",
             "наводнение", "торнадо", "смерч", "засуха", "лесной пожар"],
            ["авиакатастрофа", "крушение самолёта", "столкновение воздушное",
             "на борту", "рейс", "Boeing"],
            ["террористические нападения", "теракт", "взрыв", "боевики", "заложники",
             "смертник", "перестрелка", "ИГИЛ", "талибы вооружённые"],
            ["техногенные аварии", "утечка", "авария атомная", "загрязнение", "пожар", "АЭС", "взрыв на заводе"],
            ["война", "конфликт", "вторжение"],
            ["санкции", "пакет санкций"],
            ["выборы", "голос", "инаугурация", "импичмент"],
            ["рынок нефти", "баррель", "ОПЕК"],
            ["биткоин", "криптовалюта"],
            ["ракетный пуск", "ядерная программа", "ядерное оружие"],
            ["Nvidia", "Microsoft", "Google", "Samsung", "Huawei", "Facebook", "Apple"]
        ]
    )
    topics, probs = topic_model.fit_transform(texts)
    topic_model.reduce_topics(texts, nr_topics=15)
    topics = topic_model.topics_
    topic_model.save(MODEL_PATH_15)
    print(f"Модель обучена и сохранена в {MODEL_PATH_15}")

topic_model.get_topic_info()

Модель загружена из ../models/bertopic_events_15topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1370,-1_по_на_мира_россии,"[по, на, мира, россии, президент, президента, ...",[В первом туре парламентских выборов в Маврита...
1,0,1043,0_победу_выборов_премьер_президента,"[победу, выборов, премьер, президента, тур, вт...",[второй тур выборов президента Польши. Победу ...
2,1,782,1_человек_погибли_результате_война,"[человек, погибли, результате, война, на, ране...",[Во Владикавказе на вещевом рынке «Фаллой» взо...
3,2,694,2_союз_на_погибли_человек,"[союз, на, погибли, человек, сша, станции, чел...",[старт космического корабля Союз ТМА-09М к меж...
4,3,455,3_россии_рф_россия_на,"[россии, рф, россия, на, российской, украины, ...",[инаугурация президента России Владимира Влади...
5,4,350,4_мира_по_саммит_европы,"[мира, по, саммит, европы, международный, сост...",[чемпионат мира по спортивной гимнастике (Бель...
6,5,280,5_человек_погибли_более_произошло,"[человек, погибли, более, произошло, без, резу...","[землетрясение магнитудой до 7,1 в Китае. Поги..."
7,6,150,6_военный_президента_президент_ким,"[военный, президента, президент, ким, чен, южн...",[Ким Сок Су назначен на пост премьер-министра ...
8,7,133,7_закон_европейского_ес_совета,"[закон, европейского, ес, совета, силу, стала,...",[Польша стала государством-председателем Совет...
9,8,111,8_отношения_израиль_израиля_между,"[отношения, израиль, израиля, между, соглашени...",[Хорватия и Камерун установили дипломатические...
10,9,86,9_microsoft_компания_выход_китая,"[microsoft, компания, выход, китая, китае, сис...",[Компания «Microsoft» представила «Windows 11»...
11,10,79,10_отставку_премьер министр_президент_министр,"[отставку, премьер министр, президент, министр...",[премьер-министр Грузии Мамука Бахтадзе ушёл в...
12,11,65,11_принятие_против_россии_сша,"[принятие, против, россии, сша, запрет, на, вс...",[Принятие седьмого пакета санкций против Росси...
13,12,34,12_19_коронавируса_млн_мире,"[19, коронавируса, млн, мире, пандемии, органи...",[число заражённых COVID-19 в мире превысило 40...
14,13,13,13_началось_шоу_программы_привело,"[началось, шоу, программы, привело, войне, отк...",[кризис на Чешском телевидении: спорное назнач...

In [46]:
topics, probs = topic_model.transform(texts)

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-03-27 23:58:20,636 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

In [47]:
sample_docs_per_topic(texts, topics, n_samples=10)

topic -1 | total docs: 243
================================================================================
TOPIC 0 | total docs: 1163
================================================================================
1. в Молдавии состоялся второй тур всеобщих местных выборов. По всей территории Молдавии процент явки избирателей составил 58,68 %, а в Кишинёве 45,43 %, что достаточно для признания выборов состоявшимися. На выборах были избраны районные и муниципальные, городские и сельские советы, а также 1295 примаров.
2. введение национальной валюты, «сомони», в Республике Таджикистан.
3. Выборы президента Колумбии.
4. президентские выборы на Мадагаскаре.
5. Парламентские выборы в Италии.
6. парламентские выборы в Словакии, формирование коалиции социал-демократической партии Курс — социальная демократия, популистского Движения за демократическую Словакию и националистической Словацкой национальной партии.
7. в Кыргызстане по результатам референдума были одобрены поправки к Конституции, а президент Аскар Акаев получил возможность оставаться в должности до 2005 года.
8. вступила в должность президент Молдовы Майя Санду.
9. Дрис Жетту назначен премьер-министром Марокко (до 15 октября 2007 года).
10. выборы в Европарламент.

================================================================================
TOPIC 1 | total docs: 646
================================================================================
1. в 16:03-16:05 в Пятигорске и Невинномысске одновременно прогремели четыре взрыва. Первый взрыв произошёл на автобусной остановке на улице Гагарина рядом с администрацией Невинномысска, второй — на Казачьем рынке Невинномысска, третий и четвёртый взрывы произошли на платформе железнодорожного вокзала в Пятигорске. В результате терактов 4 человека погибли, 20 ранены.
2. попытка поджога Рейхстага в Берлине. 22-летний немец на своём автомобиле «Volkswagen Golf» попытался сквозь стеклянные витрины прорваться внутрь здания, однако машина застряла. Позже выяснилось, что она была облита со всех сторон бензином.
3. Арабо-израильский конфликт: в результате взрыва автобуса Тель-Авив — Назарет террористом-смертником 6 человек погибли, более 30 получили ранения.
4. авария на шахте «Юбилейная» в Новокузнецке, в результате которой погибло 39 человек.
5. в магазине одежды «Lane Bryant» в Тинли-Парке произошла кровавая бойня.???
6. теракт в Пешаваре; 63 погибших, около 200 раненых.
7. В Мюнхене (Германия) в результате наезда на толпу участников митинга профсоюзной организации ver.di погибли, как минимум, двое человек, и более 30 пострадали.
8. на первом этаже рижского универмага Centrs произошли два мощных взрыва, количество пострадавших составило около 30 человек, одна женщина умерла от полученных ранений.
9. теракт на кладбище в Кермане (Иран). В результате двух взрывов погибли не менее 94 человек, более 170 получили ранения. Ответственность за теракт взяло на себя афганское отделение «Исламского государства».
10. в Астраханской области произошли калмыцко-чеченские межэтнические столкновения, начавшиеся с осквернения чеченцами памятника, установленного погибшему в ходе Второй Чеченской войны военнослужащему

================================================================================
TOPIC 2 | total docs: 633
================================================================================
1. состоялся запуск российского космического корабля Союз МС-17 с космодрома «Байконур».
2. С космодрома Ясный (Россия) произведён запуск второго казахстанского спутника космической системы дистанционного зондирования Земли KazEOSat-2.
3. открытие планеты Глизе 581c.
4. специалисты НАСА обнаружили доказательства наличия на Марсе потоков солёной воды.
5. «Вояджер-2» обогнал «Пионера-10» как второй по расстоянию от Солнца космический аппарат.
6. миссия шаттла «Дискавери» к МКС.
7. Старт космического корабля «Союз ТМ-30». Экипаж — С. В. Залётин и А. Ю. Калери
8. лунный зонд «SMART-1» вышел на рабочую орбиту.
9. С космодрома «Плесецк» запущена ракета-носитель «Ангара-1.2ПП».
10. НАСА запустило автоматической межпланетной станции «Юнона» для исследования Юпитера.

================================================================================
TOPIC 3 | total docs: 732
================================================================================
1. первое в истории столкновение американского и российского спутников.
2. Юрий Лужков и Валерий Шанцев переизбраны на посту мэра и вице-мэра Москвы, Алексей Якуничев переизбран главой Вологды, а в Екатеринбурге состоялся первый тур выборов главы города.
3. Президент РФ Владимир Путин и федеральный канцлер ФРГ Ангела Меркель открыли в Дрездене памятник Фёдору Михайловичу Достоевскому работы народного художника России Александра Рукавишникова.
4. Президент РФ Дмитрий Медведев подписал федеральный закон «О полиции».
5. в Москве между Россией и США подписан договор о сокращении стратегических наступательных потенциалов. Условия договора ограничивают количество ядерных боеголовок, стоящих на боевом дежурстве, до 1700—2200 для каждой из сторон (вступил в силу 1 июня 2003 года после совместной ратификации Россией и США).
6. в России на телеканале ОРТ состоялась премьера телеигры «Русская Рулетка» (ведущий — Валдис Пельш) (выходила до 6 августа 2004 года).
7. вступил в должность президент Южной Осетии Леонид Тибилов.
8. в России указом президента России создан АО «Концерн ПВО Алмаз-Антей».
9. Таможенный союз Беларуси, Казахстана и России открыл внутренние границы.
10. Президент России Дмитрий Медведев подписал закон о либерализации уголовного законодательства.

================================================================================
TOPIC 4 | total docs: 534
================================================================================
1. XIV чемпионат мира по лёгкой атлетике (Москва).
2. Михаэль Шумахер стал первым в истории гонок «Формула-1» 6-кратным чемпионом мира, побив рекорд по количеству чемпионских титулов (5)Хуана-Мануэля Фанхио, державшийся с 1957 года (рекорд был не только непревзойдённым, но и неповторённым — вторым 5-кратным чемпионом стал сам Шумахер в предыдущем, 2002 году).
3. Победа сборной Франции по футболу в Лиге наций УЕФА. Сборная обыграла в финале сборную Испании.
4. финал Кубка УЕФА в Стамбуле. Победитель — донецкий «Шахтёр».
5. 38-й Московский международный кинофестиваль.
6. в Турине (Италия) начались ХХ зимние Олимпийские игры (завершились 26 февраля).
7. чемпионат мира по хоккею на траве среди мужчин в Гааге (Нидерланды), чемпионам стали хоккеисты Австралии.
8. чемпионат мира по тяжёлой атлетике (Хьюстон, США).
9. 68-й Венецианский кинофестиваль. Приз «Золотой лев» получил фильм Александра Сокурова «Фауст».
10. в Каракасе (Венесуэла) прошёл XVI Всемирный фестиваль молодёжи и студентов.

================================================================================
TOPIC 5 | total docs: 393
================================================================================
1. произошёл крупный пожар на армейских складах недалеко от села Гусиное Озеро.
2. Землетрясение в Китае в провинциях Ганьсу и Цинхай. Погибло по меньшей мере 118 человек.
3. Большое наводнение, вызванное сильными дождями на Украине, затопило много посёлков, многие мосты были разрушены. От наводнения погиб 21 человек. Наводнением затопило города Тирасполь (Молдавия) и Черновцы (Украина).
4. запущена первая нитка газопровода «Северный поток».
5. В результате взрыва бомбы в колумбийском городе Вильявисенсио 10 человек погибли, 25 получили ранения.
6. запущен самый высокогорный газопровод «Дзуарикау — Цхинвал».
7. в северо-западной китайской провинции Ганьсу археологи обнаружили гигантскую сеть пещер. Она протянулась на расстояние более 50 километров среди отвесных скал по обе стороны реки Цзинхэ и насчитывает 512 пещер и 5 колодцев.
8. в округе Пуна штата Махараштра в Индии сошёл оползень, погибли более 70 человек.
9. Землетрясение в Индонезии магнитудой около 7.
10. Сильнейший с 2005 года ураган Харви обрушился на Техас, США.

================================================================================
TOPIC 6 | total docs: 273
================================================================================
1. в столице Индонезии Джакарте открылась первая линия метрополитена.
2. в Чаде вторая попытка повстанцев захватить столицу после 2006 года.
3. бывший президент Перу Алан Гарсия покончил с собой, когда полицейские прибыли в его дом в Лиме, столице страны, чтобы задержать в рамках расследования дела о коррупции.
4. Лопес Обрадор официально вступил в должность президента Мексики.
5. Премьер-министром Йемена стал лидер оппозиции Мухаммад Басиндва.
6. в Демократической Республике Конго совершена неудавшаяся попытка государственного переворота, убиты около 40 боевиков.
7. Венесуэлец Альваро Сильва Кальдерон вступил в должность Генерального секретаря ОПЕК (до 31 декабря 2003 года).
8. В Мавритании совершён военный переворот.
9. Корейская Народно-Демократическая Республика расторгла договор о ненападении с Корейской республикой.
10. беспорядки начались по всей Папуа — Новой Гвинее после того, как предполагаемая ошибка округления привела к сокращению заработной платы сотрудникам полиции и солдатам.

================================================================================
TOPIC 7 | total docs: 244
================================================================================
1. официально подтверждено получение 118-го элемента.
2. в Словакии состоялся референдум о вступлении в ЕС. В голосовании приняло участие более 52,15 % процентов зарегистрированных избирателей и более 90 % из них высказались в поддержку вступления Словакии в Евросоюз.
3. Польша принимает председательство в Совете Европейского Союза после Венгрии.
4. в Астане (Казахстан) подписан договор о создании Евразийского экономического союза.
5. новым федеральным канцлером Австрии стал Кристиан Керн.
6. Европарламент проголосовал за вхождение Румынии и Болгарии в Шенгенскую зону, но Нидерланды заблокировали это решение, отложив рассмотрение до 2012 года.
7. в Европе произошло крупнейшее за последние 100 лет наводнение: сильнее всего пострадали Чехия, Австрия, Германия, Словакия, Польша, Венгрия, Румыния и Хорватия.
8. во Франции началось социальное движение Ночное стояние.
9. Венгрия, Кипр, Латвия, Литва, Мальта, Польша, Словакия, Словения, Чехия и Эстония вошли в состав Европейского союза.
10. Канада и Дания закончили территориальный спор за остров Ханс. Страны договорились о разделе острова: 40 % Канаде, 60 % Дании.

================================================================================
TOPIC 8 | total docs: 256
================================================================================
1. Таджикистан присоединился к программе НАТО «Партнёрство во имя мира».
2. Начало гражданской войны в Сирии.
3. между Индией и Бангладеш произошёл пограничный конфликт, в ходе которого погибли десятки человек.
4. президент США Дональд Трамп подписал декларацию о признании США суверенитета Израиля над Голанскими высотами.
5. Израиль объявил о переходе в состояние войны впервые с 1973 года. В этот же день начались протесты против вторжения ХАМАСа и войны в Израиле.
6. США и Великобритания завершили вывод войск из Афганистана.
7. подписан Меморандум о взаимопонимании между правительством Анголы и руководством УНИТА. Формальное окончание ангольской гражданской войны.
8. в Израиле вступил в силу закон о гражданском браке для нерелигиозных граждан.
9. Армия обороны Израиля нанесла удар по офису ХАМАСа в Катаре.
10. В Судане вспыхнули бои между Суданскими вооружёнными силами и военизированными Силами быстрого реагирования (СБР). СБР захватили международный аэропорт Хартума и президентский дворец в Хартуме.

================================================================================
TOPIC 9 | total docs: 110
================================================================================
1. Apple представила свою операционную систему MacOS High Sierra.
2. снят с производства iPhone 2G.
3. Компания «Microsoft» выпустила операционную систему «Windows XP».
4. начало работы крупнейшей в мире социальной сети Facebook.
5. представлено первое поколение плеера iPod.
6. выход Windows Server 2003.
7. компания Microsoft объявляет о своём намерении приобрести Activision Blizzard за 68,7 млрд $. Сделка стала крупнейшим на тот момент приобретением компании.
8. официально введена в эксплуатацию крупнейшая в мире ГЭС «Санься» (Китай), общей мощностью 22,4 млн кВт.
9. запущен сайт Duolingo
10. корпорация Microsoft прекратила расширенную поддержку ОС Windows XP.

================================================================================
TOPIC 10 | total docs: 228
================================================================================
1. исполняющий обязанности президента Буркина-Фасо Набере Оноре Траоре отказался от власти. Исполняющим обязанности президента и премьер-министром провозгласил себя начальник охраны президента Исаак Зиада.
2. Исполняющий обязанности президента Перу Мануэль Мерино ушёл в отставку.
3. Президент Словении Борут Пахор распустил парламент страны.
4. конституционный суд Кувейта принял решение о роспуске парламента страны и проведении досрочных парламентских выборов.
5. президент Египта Хосни Мубарак покинул свой пост.
6. президент Украины Виктор Ющенко издал указ о роспуске Верховной Рады. Коалиция отказалась признавать указ.
7. премьер-министр Серж Саргсян подал в отставку.
8. Конституционный суд Молдовы принял решение временно приостановить полномочия президента Игоря Додона на время подписания указа об утверждении кандидатур министров и вице-премьеров.
9. Махатхир Мохамад ушёл в отставку с поста премьер-министра Малайзии. Он возглавлял страну более 22 лет. Абдулла Ахмад Бадави стал новым премьер-министром.
10. Палата представителей США впервые в американской истории отправила спикера Кевина Маккарти в отставку.

================================================================================
TOPIC 11 | total docs: 63
================================================================================
1. в Аргентине введены жёсткие ограничения на снятие наличных денег с банковских счетов — $250 в неделю.
2. Принят 13 пакет санкций против России.
3. Аргентина объявила дефолт по кредитам Всемирного банка.
4. вступил в силу Киотский протокол, без поддержки США и Австралии.
5. Принятие второго пакета санкций против России.
6. проблем, связанных с ростом цен на нефть
7. Впервые в американской истории большое жюри Нью-Йорка предъявило бывшему президенту США Дональду Трампу обвинение, связанное с выплатой денег за молчание порноактрисе Сторми Дэниэлс незадолго до выборов 2016 года.
8. Принятие пятого пакета санкций против России.
9. Цена на нефть марки Brent опустилась ниже $35 долларов за баррель, дневное падение цены более 20 %, это крупнейшее падение цен на нефть со времён войны в Персидском заливе. Нефтяные котировки ушли ниже цены отсечения для российского бюджета по бюджетному правилу;
10. Полное снятие в КНР ограничений на инвестиции иностранного капитала в местный автопром.

================================================================================
TOPIC 12 | total docs: 72
================================================================================
1. Австралийскими учёными обнаружен ген эпилепсии.
2. одобрение ВОЗ первой вакцины против малярии.
3. проведение Летних Олимпийских игр 2020 в Токио, перенесённые с 2020 года из-за пандемии «COVID-19».
4. Солнечное затмение на территории Европы, Ближнего Востока, Центральной Азии, Западной Сибири и северо-востоке Африки.
5. 28-я Конференция ООН по изменению климата.
6. Началось распространение COVID-19;
7. В США прошла перепись населения;
8. вопросов, связанных с изменением климата из-за возрастающего выброса в атмосферу промышленных газов
9. ВОЗ признала вспышку коронавируса чрезвычайной ситуацией в области общественного здравоохранения, имеющей международное значение. Случаи заражения были впервые зафиксированы в России, Италии и Великобритании;
10. начало вспышки метапневмовируса человека (hMPV) в Китае.

================================================================================
TOPIC 13 | total docs: 55
================================================================================
1. Началось отключение аналогового телевещания в Беларуси.
2. начало информационного вещания телеканала «Вести».
3. Приостановила свою деятельность первая в мире онлайновая радиостанция KPIG: у неё не нашлось денег на авторские отчисления.
4. Премьера Comedy Club на ТНТ.
5. выход альбома Sounds Of The Universe группы Depeche Mode.
6. РТР сменило название телеканала «Россия».
7. представлена игровая видеоприставка Uzebox, которую может спаять самостоятельно любой радиолюбитель.
8. кризис на Чешском телевидении: спорное назначение Иржи Годача генеральным директором и его попытка приватизировать общественное телевидение привело к войне за эфирное время и началу массовой цензуры на телевидении.
9. завершение показа реалити-шоу Дом-2 на телеканале ТНТ.
10. Итальянский парламент принял спорный закон о средствах массовой информации, позволяющий премьер-министру Сильвио Берлускони, крупнейшему медиа-магнату страны, контролировать 90 процентов итальянских телеканалов и приобретать в собственность новые печатные издания и радиостанции. Критики закона назвали ситуацию «концом свободы информации».

In [48]:
print('=== 15-topics модель: barchart тем ===')
visualize_topics_barchart(topic_model)

=== 15-topics модель: barchart тем ===
Dash app running on http://127.0.0.1:10013/

In [49]:
print('=== 15-topics модель: scatter документов по темам ===')
visualize_documents_scatter(topic_model, texts, topics)

=== 15-topics модель: scatter документов по темам ===
Dash app running on http://127.0.0.1:10014/