In [1]:
import re

import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/events/2_struct/2000-2025.csv')

df.head()

   date_start date_end                                              event
0  2000-01-01      NaN                    Деноминация белорусского рубля;
1  2000-01-01      NaN  В связи с «проблемой-2000», в Иране объявлен н...
2  2000-01-01      NaN  Вступление в силу закона в Великобритании, сог...
3  2000-01-02      NaN  крушение украинского сухогруза типа «река-море...
4  2000-01-03      NaN  Обстрел из гранатомёта территории российского ...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5645 entries, 0 to 5644
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date_start  5645 non-null   object
 1   date_end    603 non-null    object
 2   event       5645 non-null   object
dtypes: object(3)
memory usage: 132.4+ KB

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

ru_stopwords = stopwords.words("russian")


def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"[^а-яё\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


texts = df["event"].dropna().astype(str).apply(clean_text)

vectorizer = TfidfVectorizer(
    max_df=0.9,
    min_df=5,
    stop_words=ru_stopwords,
    ngram_range=(1, 3),
    sublinear_tf=True,
)
X = vectorizer.fit_transform(texts)

n_topics = 10
model = NMF(n_components=n_topics, random_state=42)
W = model.fit_transform(X)
H = model.components_

feature_names = vectorizer.get_feature_names_out()
topics = {}
for i, topic in enumerate(H):
    top_words = [feature_names[j] for j in topic.argsort()[:-11:-1]]
    topics[f"Topic {i + 1}"] = top_words

print(len(vectorizer.vocabulary_))
topics

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ruslan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

3311

{'Topic 1': ['парламентские выборы',
  'парламентские',
  'выборы',
  'досрочные парламентские',
  'досрочные парламентские выборы',
  'досрочные',
  'партия',
  'большинство',
  'сирии',
  'мест'],
 'Topic 2': ['человек',
  'погибли',
  'погибли человек',
  'результате',
  'человека',
  'человек погибли',
  'получили',
  'ранены',
  'ранения',
  'погибло'],
 'Topic 3': ['должность',
  'вступил',
  'должность президента',
  'президента',
  'вступил должность',
  'вступил должность президента',
  'года',
  'президент',
  'должность президент',
  'вступил должность президент'],
 'Topic 4': ['тур',
  'выборов',
  'президентских',
  'президентских выборов',
  'второй',
  'второй тур',
  'тур президентских',
  'тур президентских выборов',
  'второй тур президентских',
  'одержал'],
 'Topic 5': ['мира',
  'чемпионат',
  'чемпионат мира',
  'россия',
  'мира хоккею',
  'хоккею',
  'чемпионат мира хоккею',
  'сборная',
  'мира хоккею шайбой',
  'хоккею шайбой'],
 'Topic 6': ['премьер',
  'министром',
  'премьер министром',
  'стал',
  'новым',
  'новым премьер министром',
  'новым премьер',
  'министра',
  'премьер министра',
  'назначен'],
 'Topic 7': ['сша',
  'союз',
  'корабля',
  'экипаж',
  'корабля союз',
  'тма',
  'союз тма',
  'космического',
  'космического корабля',
  'космического корабля союз'],
 'Topic 8': ['президентские',
  'президентские выборы',
  'выборы',
  'одержал',
  'победу одержал',
  'победу',
  'президент',
  'действующий',
  'действующий президент',
  'избран'],
 'Topic 9': ['россии',
  'день',
  'единый',
  'голосования',
  'против',
  'единый день голосования',
  'единый день',
  'день голосования',
  'голосования россии',
  'день голосования россии'],
 'Topic 10': ['одержала',
  'победу',
  'победу одержала',
  'партия',
  'правящая',
  'парламентских',
  'сборная',
  'одержала правящая',
  'победу одержала правящая',
  'оппозиционная']}

In [5]:
from sklearn.decomposition import TruncatedSVD

n_topics = 10

lsa = TruncatedSVD(
    n_components=n_topics,
    random_state=42
)

X_lsa = lsa.fit_transform(X)
feature_names = vectorizer.get_feature_names_out()

topics = {}

for i, comp in enumerate(lsa.components_):
    indices = np.argsort(np.abs(comp))[-12:]
    top_words = [feature_names[j] for j in indices]
    topics[f"Topic {i + 1}"] = top_words

topics

{'Topic 1': ['тур',
  'победу одержала',
  'победу одержал',
  'одержал',
  'одержала',
  'партия',
  'президентские выборы',
  'президентские',
  'победу',
  'парламентские выборы',
  'парламентские',
  'выборы'],
 'Topic 2': ['президента',
  'погибло',
  'получили ранения',
  'ранены',
  'ранения',
  'получили',
  'человек погибли',
  'человека',
  'результате',
  'погибли человек',
  'погибли',
  'человек'],
 'Topic 3': ['одержал',
  'погибли',
  'человек',
  'тур',
  'выборов',
  'парламентские',
  'парламентские выборы',
  'вступил должность',
  'должность президента',
  'вступил',
  'президента',
  'должность'],
 'Topic 4': ['одержал',
  'победу',
  'второй',
  'президентских выборов',
  'второй тур',
  'президентских',
  'вступил должность',
  'должность президента',
  'выборов',
  'тур',
  'вступил',
  'должность'],
 'Topic 5': ['хоккею шайбой',
  'мира хоккею шайбой',
  'шайбой',
  'одержала',
  'чемпионат мира хоккею',
  'хоккею',
  'мира хоккею',
  'сборная',
  'россия',
  'чемпионат мира',
  'чемпионат',
  'мира'],
 'Topic 6': ['министра',
  'президента',
  'вступил',
  'должность',
  'должность президента',
  'новым премьер',
  'новым премьер министром',
  'новым',
  'стал',
  'премьер министром',
  'министром',
  'премьер'],
 'Topic 7': ['союз тма экипаж',
  'корабля союз тма',
  'космического корабля союз',
  'космического корабля',
  'космического',
  'союз тма',
  'тма',
  'корабля союз',
  'экипаж',
  'корабля',
  'союз',
  'сша'],
 'Topic 8': ['тур президентских',
  'победу одержал',
  'одержал',
  'тур',
  'президентских',
  'президентских выборов',
  'выборов',
  'выборы',
  'парламентские',
  'парламентские выборы',
  'президентские',
  'президентские выборы'],
 'Topic 9': ['день голосования россии',
  'президентские',
  'президентские выборы',
  'президент',
  'против',
  'день голосования',
  'единый день',
  'единый день голосования',
  'голосования',
  'единый',
  'день',
  'россии'],
 'Topic 10': ['выборы',
  'первый',
  'тур',
  'президента',
  'победу одержал',
  'одержал',
  'партия',
  'президентские',
  'президентские выборы',
  'победу одержала',
  'одержала',
  'победу']}

In [6]:
from sklearn.decomposition import LatentDirichletAllocation

n_topics = 10
lda = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    learning_method="batch",
    max_iter=30,
    doc_topic_prior=0.1,  # alpha
    topic_word_prior=0.01  # beta
)
X_lda = lda.fit_transform(X)

feature_names = vectorizer.get_feature_names_out()
topics = {}
for i, topic_dist in enumerate(lda.components_):
    top_idx = topic_dist.argsort()[-12:][::-1]
    topics[f"Topic {i + 1}"] = [feature_names[j] for j in top_idx]

topics

{'Topic 1': ['стал',
  'министром',
  'премьер министром',
  'премьер',
  'новым',
  'референдум',
  'сша',
  'президентом',
  'новым премьер',
  'новым премьер министром',
  'великобритании',
  'конституционный'],
 'Topic 2': ['космический',
  'союз',
  'россии',
  'рф',
  'союз тма',
  'тма',
  'корабль',
  'аппарат',
  'посадки',
  'сша',
  'казахстане',
  'представителей'],
 'Topic 3': ['россия',
  'впервые',
  'сша',
  'европы',
  'станции',
  'истории',
  'второй тур выборов',
  'тур выборов',
  'старт',
  'выборов президента',
  'полёт',
  'оон'],
 'Topic 4': ['человек',
  'погибли',
  'результате',
  'погибли человек',
  'человека',
  'погибло',
  'ранены',
  'получили',
  'человек погибли',
  'ранения',
  'взрыв',
  'получили ранения'],
 'Topic 5': ['парламентские выборы',
  'парламентские',
  'выборы',
  'премьер',
  'президент',
  'министра',
  'премьер министра',
  'года',
  'должность',
  'министр',
  'вступил',
  'отставку'],
 'Topic 6': ['сша',
  'корабля',
  'россии',
  'космического',
  'ес',
  'первый',
  'космического корабля',
  'союз',
  'населения',
  'вышли',
  'мкс',
  'владимира'],
 'Topic 7': ['выборы',
  'победу',
  'выборов',
  'президентские',
  'тур',
  'президентские выборы',
  'одержал',
  'партия',
  'победу одержал',
  'парламентские',
  'парламентские выборы',
  'второй'],
 'Topic 8': ['мира',
  'чемпионат',
  'чемпионат мира',
  'саммит',
  'россии',
  'сборная',
  'открыт',
  'компания',
  'германия',
  'обязанности',
  'россия',
  'мира хоккею'],
 'Topic 9': ['землетрясение',
  'убийство',
  'магнитудой',
  'российской',
  'отношения',
  'федерации',
  'дипломатические',
  'дипломатические отношения',
  'беспорядки',
  'российской федерации',
  'произошло',
  'массовые'],
 'Topic 10': ['президента',
  'должность',
  'должность президента',
  'вступил',
  'вступил должность',
  'вступил должность президента',
  'международный',
  'официально',
  'республики',
  'вступила',
  'нато',
  'кинофестиваль']}

In [7]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

texts = df["event"]

embedding_model = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

vectorizer_model = CountVectorizer(
    ngram_range=(1, 3),
    min_df=5
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True,
)

topics, probs = topic_model.fit_transform(texts)

2026-03-01 21:10:37,945 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-03-01 21:11:21,320 - BERTopic - Embedding - Completed ✓
2026-03-01 21:11:21,321 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-01 21:11:37,708 - BERTopic - Dimensionality - Completed ✓
2026-03-01 21:11:37,709 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-01 21:11:39,358 - BERTopic - Cluster - Completed ✓
2026-03-01 21:11:39,362 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-01 21:11:39,653 - BERTopic - Representation - Completed ✓

In [8]:
import random
from collections import defaultdict


def sample_docs_per_topic(texts, topics, n_samples=10, seed=42):
    random.seed(seed)

    topic_to_docs = defaultdict(list)
    for text, topic in zip(texts, topics):
        topic_to_docs[topic].append(text)

    for topic_id, docs in sorted(topic_to_docs.items()):
        if topic_id == -1:
            print(f"topic {topic_id} | total docs: {len(docs)}")
            continue

        print("=" * 80)
        print(f"TOPIC {topic_id} | total docs: {len(docs)}")
        print("=" * 80)

        sampled = random.sample(docs, min(n_samples, len(docs)))
        for i, doc in enumerate(sampled, 1):
            print(f"{i}. {doc}")
        print()


def save_topics_barchart(topic_model: BERTopic, out_html="topics_barchart.html", top_n_topics=30):
    """
    Сохраняет интерактивный bar chart с размерами/словами тем (BERTopic).
    """
    fig = topic_model.visualize_barchart(top_n_topics=top_n_topics, n_words=10)
    fig.write_html(out_html)
    return fig


def save_documents_scatter(topic_model, texts, topics, out_html="documents_scatter.html"):
    """
    Сохраняет интерактивный scatter документов по темам (BERTopic).
    """
    fig = topic_model.visualize_documents(docs=texts, topics=topics)
    fig.write_html(out_html)
    return fig

In [9]:
topic_model.get_topic_info().head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1394,-1_чемпионат_по_мира по_чемпионат мира по,"[чемпионат, по, мира по, чемпионат мира по, че...",[чемпионат мира по футболу в Катаре. Победу од...
1,0,180,0_перу_всеобщие_чили_президента,"[перу, всеобщие, чили, президента, всеобщие вы...",[второй тур президентских выборов в Аргентине....
2,1,146,1_самолёт_борту_на борту_все,"[самолёт, борту, на борту, все, разбился, ката...","[самолёт Ан-148, выполнявший рейс из Москвы в ..."
3,2,135,2_протеста_против_массовые_протесты,"[протеста, против, массовые, протесты, началис...",[В Турции начались массовые протесты с требова...
4,3,125,3_казахстана_казахстане_кыргызстана_армении,"[казахстана, казахстане, кыргызстана, армении,...",[Президентские выборы в Казахстане. Победил де...
5,4,104,4_результате взрыва_взрыва_результате_погибли,"[результате взрыва, взрыва, результате, погибл...",[В результате взрыва на химическом заводе во ф...
6,5,102,5_сербии_хорватии_словакии_тур,"[сербии, хорватии, словакии, тур, выборах, пар...",[Президентские и парламентские выборы в Сербии...
7,6,100,6_союз_корабля_космического корабля_космического,"[союз, корабля, космического корабля, космичес...",[приземление космического корабля Союз ТМА-01М...
8,7,86,7_сирии_ирака_ираке_аль,"[сирии, ирака, ираке, аль, войска, коалиции, б...","[Парламентские выборы в Сирии., Парламентские ..."
9,8,84,8_саммит_государств_конференция_глав,"[саммит, государств, конференция, глав, нато, ...","[саммит АТЭС (Манила, Филиппины)., саммит ШОС ..."

In [10]:
sample_docs_per_topic(texts, topics, n_samples=10)
save_topics_barchart(topic_model, out_html="../reports/topic_plots/bertopic_events_auto_barchart.html")
save_documents_scatter(topic_model, texts, topics, out_html="../reports/topic_plots/bertopic_events_auto_scatter.html")

topic -1 | total docs: 1394
================================================================================
TOPIC 0 | total docs: 180
================================================================================
1. всеобщие выборы в Мексике. Клаудия Шейнбаум была избрана первой женщиной-президентом Мексики.
2. Абель Пачеко вступил в должность президента Коста-Рики (до 8 мая 2006 года).
3. Альберто Фухимори переизбран президентом Перу. Оппозиция не признала выборы и ответила новыми маршами протеста, в которых участвовали сотни тысяч людей. Полиция жестоко подавляла выступления. В ходе столкновений сотни людей были ранены и арестованы.
4. Выборы президента Венесуэлы. Победу одержал Николас Мадуро, однако сторонники оппозиционного кандидата Энрике Каприлеса не признали результаты выборов.
5. Президентские выборы в Гватемале. По предварительным данным, победу одержал Отто Перес Молина.
6. VI-й съезд Коммунистической партии Кубы принял решение о серьёзных политических и экономических реформах в стране.
7. В Бразилии состоялись президентские выборы. Победу одержал Луис Инасиу Лула да Силва (61.3 % голосов избирателей; вступил в должность 1 января 2003 года; до 1 января 2011 года). Второе место занял Жозе Серра (38.7 % голосов). явка составила 82,3 %.
8. Во втором туре президентских выборов в Коста-Рике победил Абель Пачеко (58,0 % голосов), опередивший Роландо Арайу Монге (42,0 % голосов).
9. Всеобщие выборы в Эквадоре.
10. всеобщие выборы в Коста-Рике.

================================================================================
TOPIC 1 | total docs: 146
================================================================================
1. Под Джокьякартой потерпел катастрофу Boeing 737 компании Garuda Indonesia, в результате которой 1 человек погиб.
2. на Кубе разбился военно-транспортный самолёт Ан-26. Погибли 39 человек (по официальной информации властей Кубы — 8 человек).
3. В аэропорту имени Чан Кайши при взлёте разбился Boeing 747 компании Singapore Airlines, погибли 83 из 179 человек на борту.
4. Самолёт Airbus A320-212 авиакомпании Gulf Air упал в Персидский залив, погибли 143 человека.
5. В районе Ипьялеса (Колумбия) потерпел катастрофу Boeing 727—134 компании TAME, в результате чего погибли 94 человека.
6. аварийная посадка A320 в Лос-Анджелесе. Погибших и пострадавших нет.
7. Grumman G-73T Turbine Mallard разбился при взлёте в Майами.
8. катастрофа Boeing 737 в Тэнсяне (Китай). Погибли все 132 человека на борту.
9. катастрофа сверхзвукового авиалайнера «Конкорд» при вылете из парижского аэропорта «Шарль де Голль». Погибли все находившиеся на борту 109 человек (100 пассажиров и 9 членов экипажа), а также 4 человека на земле.
10. крушение Boeing 787 под Ахмадабадом в Индии. Самолёт упал на здание общежития. На борту находилось 242 человека. Выжил лишь один человек.

================================================================================
TOPIC 2 | total docs: 135
================================================================================
1. В Турции начались массовые протесты с требованием отставки правительства страны.
2. Начало протестов против пенсионной реформы во Франции.
3. в Балтиморе (США) в связи с гибелью афроамериканца Фредди Грея, который был убит полицией, начались демонстрации и столкновения демонстрантов с полицией, в городе был введён комендантский час.
4. беспорядки начались по всей Папуа — Новой Гвинее после того, как предполагаемая ошибка округления привела к сокращению заработной платы сотрудникам полиции и солдатам.
5. более 1 млн человек вышли на улицы городов Алжира, Орана, Константина, требуя от действующего 82-летнего президента Абдель Азиза Бутефлики не выдвигать свою кандидатуру на пятый срок.
6. На первой большой демонстрации оппозиции в 2000 году около 100 000 человек в Белграде протестуют против президента Слободана Милошевича и выступают за досрочные выборы.
7. В России и за рубежом прошли акции протеста против итогов выборов в Государственную думу Федерального собрания Российской Федерации VI созыва России.
8. в Тбилиси и по всей Грузии прошли акции протеста против закона об иноагентах.
9. В городе Москве православные активисты провели митинг против принятия закона о домашнем насилии;
10. В России начались протесты против фальсификации результатов выборов в Государственную думу РФ.

================================================================================
TOPIC 3 | total docs: 125
================================================================================
1. в Белоруссии состоялся референдум, отменивший положения конституции, которые запрещали гражданину страны занимать пост президента более двух раз подряд.
2. Парламентские выборы в Узбекистане.
3. переизбрание 64-летнего Шавката Мирзиёева, в связи с получением около 80 % голосов избирателей.
4. президент Казахстана Нурсултан Назарбаев объявил о роспуске мажилиса и назначил досрочные выборы парламента.
5. на президентских выборах в Монголии на второй срок был переизбран Нацагийн Багабанди от Монгольской народно-революционной партии .
6. введение национальной валюты, «сомони», в Республике Таджикистан.
7. выборы президента Армении. Победу одержал кандидат Серж Саргсян.
8. Во втором туре парламентских выборов в Азербайджане победу одержала партия «Новый Азербайджан», которая завоевала 75 из 125 мест.
9. досрочные выборы мажилиса Казахстана. Победу одержала Народно-демократическая партия «Нур Отан», набрав 80,99 % голосов.
10. в Каракалпакстане начались протесты против поправок в конституцию. Позже узбекские власти решили отказаться от планов по лишению Каракалпакстана автономии.

================================================================================
TOPIC 4 | total docs: 104
================================================================================
1. у отеля «Националь» в Москве террористка-смертница привела в действие взрывное устройство. Погибли 6 человек, в том числе сотрудницы ФНС РФ Инна Гизоева и Татьяна Комарова, 14 человек ранено.
2. в Турции произошла неудачная попытка госпереворота; погибли 294, ранены 1440 человек.
3. в результате трёх взрывов в ночном клубе на острове Бали (Индонезия) погибли по меньшей мере 182 человека, пострадали 300. Большинство погибших — иностранные туристы.
4. Взрыв на заводе «Эластик» в Рязанской области. Погибло 28 человек, 164 пострадали.
5. Подложенная в машину бомба взорвалась у входа в здание фондовой биржи в Джакарте (Индонезия) и вызвала цепь взрывов соседних автомобилей, погибло 15 человек.
6. Взрыв у входа в консульский отдел посольства России в Кабуле. Погибло не менее 8 человек, включая двух сотрудников посольства.
7. в Донецке (Украина) на шахте им. А. Ф. Засядько произошла самая крупная катастрофа на украинских угольных шахтах после обретения независимости в 1991 году — погиб 101 шахтёр. Через две недели, 1 декабря 2007, на том же горизонте произошёл второй взрыв — 52 горняка пострадали; на следующий день — 2 декабря 2007 — погибли 5 горноспасателей, занимавшихся ликвидацией последствий аварии.
8. авария на руднике и образование провала в Соликамске.
9. В провинции Хунань (на юго-востоке Китая) в результате взрыва на шахте погибли 25 человек.
10. Взрыв бомбы на рынке в Самаре. 10 погибших, 59 — ранено. По данным следственных органов, организатором теракта является бывший курсант Ростовского военного училища Павел Косолапов, а исполнителем преступления — житель Казахстана Еркингали Тайжанов. Последний был задержан правоохранительными органами на территории Казахстана и повесился в тюрьме.

================================================================================
TOPIC 5 | total docs: 102
================================================================================
1. На всеобщих выборах в Румынии правоцентристская коалиция потерпела сокрушительное поражение (26,37 % против 36,61 % у левоцентристов);
2. Парламентские выборы в Черногории. По предварительным данным, победу одержала правящая Демократическая партия социалистов.
3. второй тур президентских выборов в Республике Македонии.
4. второй тур президентских выборов в Словакии, победу одержала Зузана Чапутова, которая стала первой в истории Словакии женщиной на посту президента.
5. досрочные парламентские выборы в Словении.
6. Второй тур выборов президента Сербии. Победу одержал Томислав Николич.
7. Президентские выборы в Сербии. Победу одержал действующий премьер-министр Александр Вучич.
8. в Сербии прошли досрочные парламентские выборы. Хотя больше всех голосов набрали радикалы Томислава Николича, но находясь в изоляции они не имели шансов получить власть. В борьбу за право сформировать правительство включились три основные реформистские партии, ранее входившие в коалицию Демократической оппозиции Сербии. Только на второй сессии в феврале удалось выбрать нового главу Скупщины. Им стал Драган Маршичанин, представитель демократов Коштуницы, кандидатуру которого поддержали депутаты от G17+, Сербского движения обновления, «Новой Сербии» и социалистов. В середине февраля лидер Демократической партии Сербии Воислав Коштуница получил мандат на формирование нового правительства Сербии. Ему удалось достичь коалиционного соглашения с G17+, Сербским движением обновления и партией «Новая Сербия», заручившись поддержкой 109 депутатов. Так как для получения парламентского большинства требовалось 126 мест из 250, Коштунице требовалась поддержка социалистов, чтобы сформировать новое правительство. Ему удалось договориться о том, что депутаты Соцпартии будут поддерживать правительство в парламенте, хотя и не получат министерские посты. 3 марта 2004 года новое сербское правительство во главе с Коштуницей пришло к власти.
9. парламентские выборы в Словакии. Партия «Курс — социальная демократия» под руководством бывшего премьер-министра Роберта Фицо получает большинство мест в Национальном совете, и эта победа вызвала международную критику из-за её предполагаемой русофилии.
10. Прошли парламентские выборы в Боснии и Герцеговине;

================================================================================
TOPIC 6 | total docs: 100
================================================================================
1. старт космического корабля Союз ТМ-33. Экипаж старта — В. М. Афанасьев, К. М. Козеев и К. Эньере (Франция).
2. космический корабль Союз ТМА-15М стартовал к международной космической станции. Экипаж в составе Антона Шкаплерова, Саманты Кристофоретти и Терри Вёртса.
3. старт космического корабля Союз ТМА-10. Экипаж старта — Ф. Н. Юрчихин, О. В. Котов и Ч. Шимоньи (Венгрия-США).
4. Запуск космического корабля «Союз МС-19» для отправки на МКС команды Первого канала для съёмок фильма «Вызов».
5. приземление космического корабля Союз ТМА-12. Экипаж посадки — С. А. Волков, О. Д. Кононенко и Р. Гэрриот (США).
6. приземление корабля Союз ТМ-34. Экипаж посадки — Ю. В. Лончаков, С. В. Залётин и Франк Де Винне (Бельгия).
7. приземление корабля «Союз ТМА-1». Экипаж посадки — Николай Бударин, Кеннет Бауэрсокс (США) и Доналд Петтит (США).
8. с космодрома Байконур стартовала ракета «Союз-ФГ» с транспортным пилотируемым кораблём «Союз ТМА-18». Экипаж старта — Александр Скворцов, Михаил Корниенко и Трейси Колдуэлл (США).
9. международные авиакассы перешли на электронные билеты.
10. международный авиационно-космический салон Aero India (Аэро Индия) (Бангалор, Индия).

================================================================================
TOPIC 7 | total docs: 86
================================================================================
1. Ахмед аш-Шараа был объявлен президентом Сирии на переходный период.
2. сирийская армия освободила Пальмиру от террористов ИГИЛ.
3. первые парламентские выборы в Ираке после свержения Социалистической партии Ирака (Баас) возглавляемой Саддамом Хуссейном.
4. Парламентские выборы в Сирии.
5. Исламское государство захватило Рамади, фактически установив контроль над всей провинцией Анбар. Иракское правительство признало потерю.
6. повешены единоутробный брат Саддама Хусейна и глава военной разведки Ирака Барзан Ибрагим ат-Тикрити и председатель революционного суда Ирака Аввад Хамид аль-Бандар.
7. столкновения на юге Сирии.
8. Военно-воздушные силы Франции, Великобритании и США начали бомбардировки районов Ливии, находящихся под контролем сторонников Каддафи.
9. В Сирии продолжаются столкновения между правительственными силами и сторонниками бывшего президента Башара Асада. По данным за 7 марта, в провинциях Латакия и Тартус погибло не менее 70 человек. Это стало крупнейшей акцией протеста против нового правительства Сирии после свержения Асада в декабре.
10. Войска коалиции заняли Мосул.

================================================================================
TOPIC 8 | total docs: 84
================================================================================
1. Саммит НАТО в США.
2. 51-й саммит G7 в Канаде.
3. саммит ЕС.
4. 31-й саммит Лиги арабских государств.
5. саммит G8 (Лох-Эрн, Великобритания).
6. саммит ОБСЕ в Астане (Казахстан).
7. Конференция по Ливии в Берлине;
8. Саммит министров сельского хозяйства G20 в Берлине, Германия.
9. Основная статья: Март 2014 года
10. Саммит НАТО в Вильнюсе.

================================================================================
TOPIC 9 | total docs: 80
================================================================================
1. трагедия на стадионе в Порт-Саиде (Египет). Погибли 74 человека, ранены порядка 300, в стране объявлен трёхдневный траур.
2. в округе Пуна штата Махараштра в Индии сошёл оползень, погибли более 70 человек.
3. Война в Афганистане: в результате взрыва на оружейном складе на юге Афганистана в городе Спин-Болдак погибли не менее 10 человек.
4. двойной теракт в Махачкале. Погибли от 12 до 14 человек, ранено около 120. В республике объявлен день траура.
5. произошла крупнейшая террористическая атака в Соединённых Штатах Америки. Был уничтожен Всемирный торговый центр, погибло порядка трёх тысяч человек, в Пентагоне пострадало левое наружное крыло, погибло 125 человек. Начало Войны против терроризма.
6. В городе Бода (ЦАР) в результате религиозных столкновений погибли 75 человек.
7. В Джубе (Южный Судан) произошли массовые беспорядки, в ходе которых погибли более 270 человек.
8. В Ираке (Багдад и Байджи) совершена серия террористических актов. Погибли более 75 человек, ранено около 150 жителей.
9. Война в Афганистане: в результате взрыва бомбы в Джелалабаде (Афганистан) погибли 12 человек.
10. Нападение радикальных исламистов на церковь Мари-Мина в Египте. Погибли 12 человек и 232 ранены.

================================================================================
TOPIC 10 | total docs: 79
================================================================================
1. В центральной части Мьянмы произошло мощное землетрясение магнитудой 7,7. Эпицентр находился вблизи города Сикайн на глубине 10 км. Через 12 минут был зафиксирован повторный толчок магнитудой 6,4. Подземные толчки ощущались в Бангкоке (Таиланд).
2. землетрясение в Мексике магнитудой 7,1 Mw в 49 км к юго-западу от мексиканского города Пуэбла-де-Сарагоса и в 100 км от столицы Мехико. Погибли 370 человек и более 6000 получили ранения.
3. по северо-западу Ирана прокатилась серия землетрясений магнитудой 6,3—6,4, в результате которой погибли 308 человек и 3037 — получили ранения.
4. Землетрясения в Герате (2023).
5. на западе Турции произошло землетрясение магнитудой от 6,6 до 6,9. Эпицентр находился в Эгейском море в 17 км от района Сеферихисар в Измире. Число погибших превысило 100 человек.
6. на Филиппинах произошло землетрясение в 7 баллов по шкале Рихтера, 10 человек погибло, 375 ранено.
7. в Чили произошло землетрясение магнитудой 6,5. Жертв и разрушений нет.
8. землетрясения в Непале магнитудой до 7,8 Mw. В Непале погибли 8699 человек, 22 489 ранены, пострадали 8 млн человек. В Индии 69 человек погибли и около 270 ранены. В Китае 25 погибших, 117 раненых.
9. землетрясение магнитудой 7,7 возле островов Ментавай к западу от Суматры в Индонезии, вызвавшее волну цунами, унесло жизни как минимум 413 человек, ещё 298 человек пропали без вести.
10. в Охотском море произошло землетрясение магнитудой 6,9 на глубине свыше 600 км. Отголоски этого землетрясения ощущались на большей части России.

================================================================================
TOPIC 11 | total docs: 76
================================================================================
1. парламентские выборы в Сенегале. Партия президента Бассиру Диомая Фая PASTEF получает абсолютное большинство в Национальной ассамблее.
2. Всеобщие выборы в Мозамбике. Даниэл Шапу избран президентом, а правящая партия ФРЕЛИМО сохраняет большинство в Ассамблее Республики.
3. Президентские выборы в Кот-д’Ивуаре. Победу одержал действующий президент Алассан Уаттара.
4. президентские выборы в Того.
5. всеобщие выборы в Демократической Республике Конго.
6. президентские выборы в Руанде. Президент Руанды Поль Кагаме, находящийся у власти с 2000 года, переизбран на новый срок. За него отдали свои голоса 99 % избирателей.
7. Парламентские выборы в Бурунди.
8. Парламентские выборы в Камеруне.
9. президентские выборы в Чаде.
10. Президентские выборы на Коморских островах: на фоне бойкота оппозиции действующий президент Азали Ассумани побеждает на переизбрании, набрав 62,9 % голосов при явке всего 16,3 % избирателей.

================================================================================
TOPIC 12 | total docs: 69
================================================================================
1. Президентские выборы в США: действующий президент Джордж Буш против сенатора Джона Керри. Победу одержал Джордж Буш.
2. Майкл Блумберг вступил в должность мэра Нью-Йорка (до 31 декабря 2013 года).
3. «Супер-вторник». День выборов делегатов на партийные съезды в США.
4. Барак Обама подписывает приказ о закрытии в течение года лагеря для интернированных в заливе Гуантанамо, где содержались неграждане, которым были предъявлены обвинения в терроризме.
5. президент США Барак Обама снял все ограничения на проведение исследований стволовых клеток эмбриона человека.
6. Джо Байден объявил о выходе из президентской гонки.
7. Сенат США преодолел вето Дональда Трампа на законопроект с санкциями против «Северного потока — 2».
8. в США прекращение полномочий президента Билла Клинтона, инаугурация Джорджа Буша-младшего. Это событие сопровождалось акциями протеста тех, кто был против прихода к власти кандидата республиканцев, получившего меньшее количество голосов избирателей, чем его соперник Альберт Гор, но признанного победителем решением Верховного суда.
9. в городе Тусон (США) во время выступления перед избирателями совершено покушение на члена Палаты представителей США от штата Аризона Габриэль Гиффордс, которая с тяжёлым ранением головы доставлена в госпиталь. Погибли 6, ранены 14 человек.
10. В возрасте 100 лет скончался 39-й президент США и лауреат Нобелевской премии мира — Джимми Картер. Картер стал самым долгоживущим президентом США и единственным который дожил до 100 лет. Государственные похороны прошли 9 января 2025 года.

================================================================================
TOPIC 13 | total docs: 69
================================================================================
1. Совместная элонгация планет Меркурия и Венеры;
2. запуск Европейским космическим агентством космического аппарата «JUICE», предназначенного для исследования спутников Юпитера.
3. Автоматическая межпланетная станция New Horizons пересекла орбиту Урана после пятилетнего путешествия.
4. получен последний сигнал от «Пионера-10» (беспилотного космического аппарата НАСА, предназначенного, главным образом, для изучения Юпитера).
5. космический аппарат Huygens совершил посадку на поверхность Титана, самого большого спутника Сатурна.
6. НАСА запустило автоматической межпланетной станции «Юнона» для исследования Юпитера.

In [11]:
# semi-supervised learning
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True,
    zeroshot_topic_list=[
        'природная катастрофа', 'авиакатастрофа', 'государственный переворот', 'вооруженный конфликт', 'теракт', 'протесты', 'санкции', 'спорт', 'закон'
    ],
    seed_topic_list=[
        ["землетрясение", "цунами", "извержение вулкана", "ураган", "тайфун",
         "наводнение", "оползень", "сель", "засуха", "лесной пожар"],
        ["авиакатастрофа", "крушение самолета", "пассажирский самолет",
         "на борту", "рейс", "экипаж"],
        ["государственный переворот", "госпереворот", "военный переворот",
 "свержение власти", "захват власти", "путч"],
        ["вооруженный конфликт", "война", "военные действия", "наступление", "обстрел", "ВС РФ", "ВСУ"],
        ["теракт", "смертник", "террористический акт"],
        ["санкции", "пакет санкций"],
        ["акция протеста", "протест", "массовые протесты", "беспорядки"],
        ["запуск ракеты", "космос", "спутник", "космический аппарат", "орбита", "космодром"],
        ["чемпионат мира", "спорт", "золотая медаль", "олимпийские игры", "сборная"],
        ["выборы президента", "выборы премьер-министра", "парламентские выборы"],
        ["закон", "подписание закона", "вступление в силу закона", "законопроект", "принятие закона"],
        ["Nvidia", "Microsoft", "Google", "Samsung", "Huawei", "Facebook", "Apple"]
    ]
)

topics, probs = topic_model.fit_transform(texts)

2026-03-01 21:12:25,960 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-03-01 21:13:07,979 - BERTopic - Embedding - Completed ✓
2026-03-01 21:13:07,980 - BERTopic - Guided - Find embeddings highly related to seeded topics.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-03-01 21:13:08,113 - BERTopic - Guided - Completed ✓
2026-03-01 21:13:08,114 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-03-01 21:13:10,606 - BERTopic - Dimensionality - Completed ✓
2026-03-01 21:13:10,607 - BERTopic - Zeroshot Step 1 - Finding documents that could be assigned to either one of the zero-shot topics
2026-03-01 21:13:10,652 - BERTopic - Zeroshot Step 1 - Completed ✓
2026-03-01 21:13:17,951 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-03-01 21:13:18,918 - BERTopic - Cluster - Completed ✓
2026-03-01 21:13:18,919 - BERTopic - Zeroshot Step 2 - Combining topics from zero-shot topic modeling with topics from clustering...
2026-03-01 21:13:18,931 - BERTopic - Zeroshot Step 2 - Completed ✓
2026-03-01 21:13:18,933 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-01 21:13:19,123 - BERTopic - Representation - Completed ✓

In [12]:
topic_model.reduce_topics(
    texts,
    nr_topics=15
)

topics, probs = topic_model.transform(texts)
topic_model.get_topic_info()

2026-03-01 21:13:19,370 - BERTopic - Topic reduction - Reducing number of topics
2026-03-01 21:13:19,562 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-01 21:13:19,800 - BERTopic - Representation - Completed ✓
2026-03-01 21:13:19,803 - BERTopic - Topic reduction - Reduced number of topics from 91 to 15

Batches:   0%|          | 0/177 [00:00<?, ?it/s]

2026-03-01 21:14:02,506 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1290,-1_по_выборы_победу_на,"[по, выборы, победу, на, россии, премьер, през...",[второй тур выборов президента Словении. Побед...
1,0,1084,0_человек_погибли_результате_на,"[человек, погибли, результате, на, более, поги...",[циклон Батсирай унёс жизни в общей сложности ...
2,1,898,1_выборы_победу_выборов_тур,"[выборы, победу, выборов, тур, президента, вто...",[второй тур выборов президента Польши. Победу ...
3,2,773,2_союз_погибли_на_человек,"[союз, погибли, на, человек, сша, станции, чел...",[в Саваре (Бангладеш) обрушилось 8-этажное зда...
4,3,459,3_россии_война_вторая_рф,"[россии, война, вторая, рф, на, федерации, ден...",[Вторая чеченская война: вертолёт Ми-8МТ МВД Р...
5,4,387,4_мира_по_саммит_международный,"[мира, по, саммит, международный, россия, евро...",[чемпионат мира по современному пятиборью (Тай...
6,5,260,5_отставку_премьер_президент_союза,"[отставку, премьер, президент, союза, югослави...",[президент Йемена Абд Раббо Мансур Хади подал ...
7,6,135,6_закон_принятие_против_силу,"[закон, принятие, против, силу, сша, президент...",[Принятие шестого пакета санкций против России...
8,7,116,7_отношения_израиль_израиля_между,"[отношения, израиль, израиля, между, оон, сша,...",[Узбекистан и Парагвай установили дипломатичес...
9,8,113,8_компания_выход_системы_сша,"[компания, выход, системы, сша, китая, мире, н...",[Обанкротилась американская компания-разработч...
10,9,47,9_президента_должность_должность президента_вс...,"[президента, должность, должность президента, ...",[Габриэль Борич вступил в должность президента...
11,10,42,10_19_всемирная_млн_мире,"[19, всемирная, млн, мире, пандемии, организац...",[число заражённых COVID-19 в мире превысило 40...
12,11,25,11_чен_южной_корея_кндр,"[чен, южной, корея, кндр, кореи, южной кореи, ...",[Конституционный суд Южной Кореи утвердил импи...
13,12,14,12_началось_прекратил_шоу_программы,"[началось, прекратил, шоу, программы, привело,...",[Началось отключение аналогового телевещания в...
14,13,2,13_нефтяной_крупнейших_крае_мировой,"[нефтяной, крупнейших, крае, мировой, истории,...","[наводнение в Приморском крае., взрыв нефтяной..."

In [13]:
sample_docs_per_topic(texts, topics, n_samples=10)

topic -1 | total docs: 247
================================================================================
TOPIC 0 | total docs: 875
================================================================================
1. на западе Турции произошло землетрясение магнитудой от 6,6 до 6,9. Эпицентр находился в Эгейском море в 17 км от района Сеферихисар в Измире. Число погибших превысило 100 человек.
2. 24 или 25 марта — на одном из крупнейших сирийских заводов по производству боеприпасов в городе Хомс произошёл взрыв. 35 человек погибли.
3. Близ острова Сулавеси потерпел крушение индонезийский паром «Кахая Бахари» (англ. «Cahaya Bahari»); погибло 492 человека;
4. убийство подростка арабского происхождения в Нантере спровоцировало массовые беспорядки.
5. Багдадский авиаудар.
6. Вооружённый мятеж в Узбекистане: захвачена тюрьма города Андижан, на свободе оказались более 4000 заключённых.
7. Иракская война: ВВС США нанесли авиаудар по Эль-Фаллудже, в результате были жертвы среди мирного населения.
8. Вторая чеченская война: в Шатое перед зданием комендатуры подорвался на фугасе ГАЗ-66 с военнослужащими: 10 человек погибли, 7 ранено.
9. Гильдия сценаристов США начала забастовку
10. в результате взрыва на угольной шахте в Шлёнском воеводстве (Польша) погибли 10 человек.

================================================================================
TOPIC 1 | total docs: 990
================================================================================
1. президентские выборы в Египте.
2. Состоялся второй тур президентских выборов в Молдове. Победу одержала Майя Санду;
3. президентские выборы в Шри-Ланке. Анура Кумара Диссанаяке избран президентом Шри-Ланки, и впервые в истории Шри-Ланки был проведён второй тур подсчёта голосов.
4. Парламентские выборы в Польше. Победу одержала оппозиционная партия «Закон и справедливость».
5. Байрам Реджепи вступил в должность премьер-министра Косово (до 3 декабря 2004 года).
6. Парламентские выборы в Республике Кипр.
7. Второй тур президентских выборов в Сальвадоре.
8. Во Франции прошёл конституционный референдум по вопросу о сокращении президентского срока с 7 до 5 лет. При относительно невысокой явке (30,2 %) подавляющее большинство избирателей (73,2 %) высказалось за сокращение срока правления.
9. во втором туре всеобщих выборов в Эфиопии победу одержала правящая коалиция РДФЭН, завоевавшая почти 90 % мест в Палате народных представителей.
10. В России состоялись выборы глав Республики Ингушетия (второй тур), Республики Карелия и Республики Бурятия. Президентом Республики Ингушетия избран Мурат Зязиков (53,13 %); его соперник Алихан Амирханов набрал 43,19 % (при явке 65,72 %). Главой Республики Карелия переизбран Сергей Катанандов (53,45 % голосов при явке 50,36 %). Главой Республики Бурятия переизбран Леонид Потапов (68,79 % при явке 53,77 %).

================================================================================
TOPIC 2 | total docs: 653
================================================================================
1. В Иркутске разбился Airbus A310 авиакомпании Сибирь. Погибли 125 человек.
2. в Сомали сбит белорусский самолёт Ил-76ТД, 11 погибших.
3. экипаж МКС в составе Олега Новицкого и Томы Песке вернулся с МКС на Землю.
4. самолёт ATR 72 разбился при заходе на посадку в Покхаре (Непал). Погибли все 72 человека на борту.
5. Проведён последний успешный сеанс связи с космическим аппаратом «Пионер-6» в честь 35-летия его запуска.
6. председатель КНР Си Цзиньпин официально заявил о начале эксплуатации глобальной навигационной спутниковой системы «Бэйдоу-3».
7. старт Шэньчжоу-6 (Китай). Экипаж — Фэй Цзюньлун, Не Хайшэн. Продолжительность полёта — 4 дня 19 часов.
8. Британская авиакомпания Flybe объявила о своём банкротстве. К прекращению деятельности компании привёл распространяющийся в мире коронавирус.
9. космический корабль Союз ТМА-08М совершил посадку в казахстанской степи. Экипаж посадки Павел Виноградов, Александр Мисуркин, Кристофер Кэссиди.
10. в Лексингтоне (Кентукки) при взлёте разбился самолёт Bombardier CRJ-100ER компании Comair, погибли 49 человек.

================================================================================
TOPIC 3 | total docs: 753
================================================================================
1. В России введено постоянное зимнее время.
2. признание Россией Донецкой и Луганской Народных Республик.
3. Центральный банк Исландии сообщил, что Россия согласилась предоставить Исландии финансовую помощь в виде ссуды размером в 4 миллиарда евро.
4. Вторая чеченская война: Взятие Грозного российской армией. Объявление исполняющего обязанности Президента РФ Владимира Путина о завершении операции по освобождению Грозного;
5. попытка заговора сотрудников ФСБ с целью покушения на Владимира Путина.
6. Единый день голосования в России.
7. Единый день голосования в России.
8. В России запрещена продажа ламп накаливания мощностью 100 ватт и более.
9. на встрече министров образования европейских государств в Берлине Россия официально вступила в Болонский процесс — единое европейское пространство высшего образования.
10. в России прошёл первый Единый день голосования.

================================================================================
TOPIC 4 | total docs: 556
================================================================================
1. чемпионат мира по шахматам среди женщин (Сочи, Россия).
2. вступление Украины в ВТО.
3. финал песенного конкурса Евровидение 2007 в Хельсинки (Финляндия).
4. чемпионат мира по биатлону (Хольменколлен, Норвегия).
5. закончился приём заявок на проведение Летних Олимпийских игр 2016 года. Заявки подали Баку, Токио, Доха, Мадрид, Прага, Чикаго и Рио-де-Жанейро.
6. 72-й Венецианский кинофестиваль.
7. саммит G7 в замке Эльмау (Бавария, Германия).
8. IV Одесский международный кинофестиваль (Одесса, Украина).
9. Армения вступила в ВТО.
10. Решение ВАДА по которому Россия была лишена права участия в соревнованиях на 4 года, права на принятие мировых соревнований;

================================================================================
TOPIC 5 | total docs: 432
================================================================================
1. Исполняющим обязанности премьер-министра Молдовы стал Георгий Брега.
2. Ян Петер Балкененде занял пост премьер-министра Нидерландов (до 14 октября 2010 года).
3. правительство Египта во главе с премьер-министром Эссамом Шарафом подало в отставку.
4. Хьель Магне Бунневик занял пост премьер-министра Норвегии.
5. В должность премьер-министра Молдовы вступил Павел Филип.
6. Чехия стала Государством-председателем Совета Европейского союза.
7. Парламент Армении принял в первом чтении законопроект «О процессе вступления Республики Армения в Европейский Союз».
8. Белит Онай избран мэром Ганновера, он стал первым этническим турком, избранным главой крупного города Германии;
9. В силу вступило соглашение между Грецией и Македонией об официальном переименовании последней в Республику Северная Македония, что положило конец спору, длившемуся с 1991 года, и открыло возможность Северной Македонии вступить в НАТО и Европейский союз;
10. Албания отменила визовый режим для граждан Украины.

================================================================================
TOPIC 6 | total docs: 135
================================================================================
1. США ввели санкции против Венесуэлы «за недостаточное сотрудничество в борьбе с терроризмом». Было принято решение ввести эмбарго на экспорт вооружений в Венесуэлу.
2. начал работу первый раздел «Википедии», wiki-энциклопедии со свободно редактируемым и распространяемым содержимым.
3. принята Директива 2000/53/ЕС, нацеленная на ограничение использования четырёх основных тяжёлых металлов (кадмия, свинца, ртути, шестивалентного хрома) в машинах.
4. в Российской Федерации введён новый вид уголовного наказания — «ограничение свободы».
5. Вступила в силу новая Конституция Грузии.
6. В Нидерландах заключены первые в мире однополые браки.
7. в России отменяется обязательная сертификация пищевой и парфюмерно-косметической продукции, а также посуды.
8. Джордж Буш подписал «Патриотический акт», давший правоохранительным органам страны широкие полномочия в борьбе с терроризмом.
9. Запрет экспорта одноразового неразлагающегося пластика в Европе.
10. Евросоюз ввёл эмбарго на импорт иранской нефти.

================================================================================
TOPIC 7 | total docs: 284
================================================================================
1. Вступление Египта, Ирана, ОАЭ, Саудовской Аравии (де-факто) и Эфиопии в состав БРИКС.
2. США официально выходят из Договора о ядерных силах средней дальности, заключённого с СССР в 1987 году.
3. в Шарм-эш-Шейхе (Египет) прошла международная конференция по Ираку. В ней участвовали главы МИД 20 стран, а также представители нескольких международных организаций. На повестке дня — обсуждение текущей ситуации в Ираке и послевоенного обустройства этой страны.
4. Иран вышел из последней ядерной сделки, заключённой в 2015 году.
5. Президент Судана Омар аль-Башир ввёл чрезвычайное положение в стране и распустил правительство, после продолжающихся третий месяц протестов.
6. палестинские группировки ФАТХ и ХАМАС подписали договор о перемирии в Сане (Йемен).
7. В Сирии принят закон об отмене чрезвычайного положения, действовавшего в стране почти полвека, и упразднён государственный суд безопасности.
8. Армения, Бруней и Буркина-Фасо установили дипломатические отношения.
9. Иран возобновил программу обогащения урана и отказался от переговоров с ЕС. Начало эскалации кризиса вокруг иранской ядерной программы.
10. Иран нанёс ракетные удары по американским военным базам в Катаре и Ираке в ответ на авиаудары США, совершённые накануне.

================================================================================
TOPIC 8 | total docs: 100
================================================================================
1. число пользователей платных подписок Apple достигло одного миллиарда.
2. начало работы крупнейшей в мире социальной сети Facebook.
3. прекращение поддержки Windows 1.0x.
4. президент США Барак Обама снял все ограничения на проведение исследований стволовых клеток эмбриона человека.
5. Microsoft официально завершила разработку ОС Windows Vista и передала её своим «Золотым партнёрам».
6. Вышла первая ревизия консоли Nintendo DS.
7. социальная сеть «Twitter» заблокировала аккаунт Дональда Трампа.
8. Илон Маск приобрёл «Twitter» за $44 млрд.
9. компания «Microsoft» выпустила операционную систему «Windows 10».
10. открыт метрополитен Дели.

================================================================================
TOPIC 9 | total docs: 229
================================================================================
1. военный переворот в Гвинее.
2. сторонники главы военной хунты капитана Амаду Саного захватили президентский дворец в Мали и потребовали отставки временного президента страны Дионкунды Траоре.
3. вступила в должность президент Молдовы Майя Санду.
4. В Эквадоре убит лидер оппозиционного движения «Гражданская революция» Педро Брионес.
5. Бразилия объявляет, что присоединится к ОПЕК+ на заседании организации для обсуждения стратегии добычи нефти в 2024 году.
6. Алехандро Толедо избран президентом Перу.
7. в Венесуэле прошёл 42-й Кубок Америки по футболу.
8. неудавшаяся попытка государственного переворота в Ла-Пасе, Боливия, во главе с бывшим главнокомандующим Хуаном Хосе Суньигой.
9. В Венесуэле проведены всеобщие и региональные выборы, президентом страны переизбран Уго Чавес (59,76 % голосов);
10. Бывший президент Бразилии Жаир Болсонару арестован по обвинению в попытке государственного переворота в рамках операции «Время истины».

================================================================================
TOPIC 10 | total docs: 83
================================================================================
1. китайский город Тяньцзинь с населением более 15 млн человек вводит военное положение в связи с вспышкой коронавируса 2019-nCoV.
2. спецслужбы Австралии, Новой Зеландии, Канады, Великобритании и США обвинили КНР в сокрытии настоящих данных о происхождении коронавируса.
3. в башкирском городе Сибай, где с ноября 2017 года держится смог, зафиксировано превышение предельно допустимой концентрации диоксида серы в 23 раза.
4. Австралийскими учёными обнаружен ген эпилепсии.
5. началась вспышка болезни Эбола: в результате 28 640 человек заразились и 11 315 погибло.
6. Япония приравняла коронавирус к категории сезонного гриппа.
7. Европейская служба по изменению климата Коперник сообщила, что 2024 год стал самым жарким годом в истории и первым календарным годом, в котором была преодолена символическая отметка в 1,5 °C глобального потепления.
8. полное солнечное затмение было видно в Мексике, центральной части США, Восточной Канаде.
9. Число заражённых COVID-19 в мире превысило 300 млн человек.
10. В Иране из-за распространения фейков новостей о способах лечения коронавируса погибли 300 человек, включая детей от отравления метанолом.

================================================================================
TOPIC 11 | total docs: 144
================================================================================
1. неудачное покушение на бывшего премьер-министра Пакистана Имрана Хана.
2. Пан Ги Мун стал Генеральным секретарём ООН.
3. военный переворот в Таиланде. В стране объявлено чрезвычайное положение, власть перешла в руки Комитета по защите национальной безопасности во главе с генералом Праютом Чан-Оча.
4. первое испытание Северной Кореей ядерного оружия.
5. в Египте произошёл государственный переворот, президент Мухаммед Мурси арестован. Исполнять обязанности президента стал председатель Верховного суда Адли Мансур.
6. В Нью-Йорке открылась восьмидесятая сессия Генеральной Ассамблеи ООН.
7. Хан Док Су по решению Конституционного суда снова стал исполняющим обязанности президента Республики Корея.
8. Президентские выборы в Южной Корее. Победу одержал Юн Сок Ёль.
9. Джефф Безос заявил об уходе с поста директора «Amazon» в третьем квартале текущего года, предложив в качестве нового директора Эндрю Джесси.
10. Начался судебный процесс над бывшим премьер-министром Малайзии Наджибом Разаком, обвиняемым в краже 700 миллионов долларов из инвестиционного фонда 1MDB;

================================================================================
TOPIC 12 | total docs: 62
================================================================================
1. Телеканал «ТНТ» сменил тематику передач на «реалити-шоу» и развлекательные программы.
2. Приостановила свою деятельность первая в мире онлайновая радиостанция KPIG: у неё не нашлось денег на авторские отчисления.
3. запуск русской версии всемирно известного телеканала Disney Channel вместо канала Jetix.
4. представлена игровая видеоприставка Uzebox, которую может спаять самостоятельно любой радиолюбитель.
5. вышло в эфир первое российское реалити-шоу «За стеклом».
6. поджог телеканала «Интер» в Киеве.
7. начало трансляции телеигры «Кто хочет стать миллионером?» на телеканале ОРТ .
8. На телеканале Fox была показана последняя серия культового американского телесериала «Секретные материалы».
9. Остров Норфолк объявил себя зоной, свободной от мобильных телефонов (запрет на пользование мобильными телефонами действовал на острове до апреля 2007 года).
10. Французская сеть Minitel прекратила своё существование из-за вытеснения Интернетом.

================================================================================
TOPIC 13 | total docs: 102
================================================================================
1. проблем, связанных с ростом цен на нефть
2. на Камчатке зафиксировано землетрясение магнитудой 7,2.
3. Падение автобуса в реку Мойку в Санкт-Петербурге. 7 человек погибли, 2 выжили.
4. инцидент в Керченском проливе.
5. подрыв грузовых вагонов на железнодорожной станции Унеча Брянской области.
6. Под Хабаровском открыт мост через Амурскую протоку длиной 750 метров.
7. В результате пожара на итальянском пароме MS Norman Atlantic в Адриатическом море погибли 13 человек, 98 пропали без вести.
8. Пуском последнего гидроагрегата завершилось восстановление Саяно-Шушенской ГЭС, на которой более пяти лет назад произошла техногенная катастрофа.
9. Американская радиостанция Hal Turner Radio Show сообщила о том, что в Южно-Китайском море на глубине 50 метров произошёл подводный ядерный взрыв мощностью от 10 до 20 килотонн в тротиловом эквиваленте.
10. в Италии произошло извержение вулкана Этна.

In [14]:
topic_model.save('../models/bertopic_events_15topics')
save_topics_barchart(topic_model, out_html="../reports/topic_plots/bertopic_events_15topics_barchart.html")
save_documents_scatter(topic_model, texts, topics, out_html="../reports/topic_plots/bertopic_events_15topics_scatter.html")

2026-03-01 21:14:02,831 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.